### ISSUE TITLE
Custom gradient in `add_heatmap` doesn't have a proper legend when the gradient only has two colours

### ISSUE THREAD

**Issue by symbalex** [SymbolixAU/googleway#100]
When I create a heatmap with weights and I use the default colour gradient (example 1), the scale is fine. When I create a heatmap with weights and I use a custom palette with lots of colours (example 3), the scale is also fine. But when I create a heatmap with weights and a two-colour palette (example 2), the scale only has the colour corresponding to the maximum weight, and doesn't have the colour corresponding to the minimum weight. Why is this?

```
library(data.table)
library(googleway)
library(viridis)

custom_pal <- googleway:::removeAlpha(viridis(2))
custom_pal2 <- googleway:::removeAlpha(viridis(10))

dt_mapping <- data.table(
  lat = seq(-40.727, -40.832, length.out = 5),
  lon = seq(148.124, 147.933, length.out = 5),
  weight = 0:4
)

map_key <- "my_api_key"

# ex. 1 - shows scale correctly
google_map(key = map_key, styles = map_styles()$silver) %>% 
  add_heatmap(data = dt_mapping, lat = "lat", lon = "lon", 
              weight = "weight", legend = TRUE)

# ex. 2 - only has one colour on the scale
google_map(key = map_key, styles = map_styles()$silver) %>% 
  add_heatmap(data = dt_mapping, lat = "lat", lon = "lon", 
              option_gradient = custom_pal, weight = "weight", legend = TRUE)

# ex. 3 - looks fine
google_map(key = map_key, styles = map_styles()$silver) %>% 
  add_heatmap(data = dt_mapping, lat = "lat", lon = "lon", 
              option_gradient = custom_pal2, weight = "weight", legend = TRUE)

```

**Comment by SymbolixAU** [comment]
From `?add_heatmap`

> The first colour in the vector will be used as the colour that fades to transparent

What this is actually saying is the first colour isn't actually part of the mapping to the data, it's the colour that will connect the 'non-colour' of the map, to the first colour of the data. 

This is working as expected in the code, but I see this isn't clear in the documentation, so I'll update it.

**Comment by SymbolixAU** [comment]
@symbalex please try the latest dev version and see if `?add_heatmap` is clearer

**Comment by symbalex** [comment]
That makes sense to me, thank you.
