### ISSUE TITLE
Consider keeping get_route() as deprecated function

### ISSUE THREAD

**Issue by jonocarroll** [SymbolixAU/googleway#11]
Rather than break anyone's code with an update, consider leaving it in (revert that file to c6b01c25bc5a86efe69aa54bc4e5e8ea8dffeb4b) for a version or two but add

```
.Deprecated("google_directions")
```

as per http://r-pkgs.had.co.nz/release.html#release-version .

Package looks good, I'll be seeing if I can integrate functionality into one of mine. Cheers.

**Comment by SymbolixAU** [comment]
I'm inclined to leave it as it is - the package had only been live for 2 weeks before I changed it and only had a handful of downloads.

**Comment by jonocarroll** [comment]
You could still leave it in without code, but adding the `.Deprecated("google_directions")` flag is an existing mechanism for what you're intending. Not a major issue, so feel free to close.
