### ISSUE TITLE
google_directions(); Valid names for waypoints list

### ISSUE THREAD

**Issue by jonocarroll** [SymbolixAU/googleway#12]
In `google_directions()`, while it is already noted that lists with elements named `via` will be processed as non-stopping waypoints, it took hunting through the source code to realise that they need to be named `""` (explicitly empty character) to be used otherwise. You have fatal testing for this in-place, but it's not documented. 

Given that you explicitly write the `via:` prefix anyway, I'd like to suggest adding `stop` to the list of valid names in your package, which can then be left out from the actual API call.

**Comment by SymbolixAU** [comment]
Good spot. I'll add a fix for the next release.
