### ISSUE TITLE
Safely access connection and control for errors

### ISSUE THREAD

**Issue by jonocarroll** [SymbolixAU/googleway#13]
I notice there's no error control around `curl::curl(map_url)`; this would not be too hard to do safely, either with `tryCatch()` or `purrr::safely()`. I'd guess that would be feedback you received from CRAN anyway.

Some processing on the returned data would be useful too; I received a few empty returns with 

```
result$status
#> [1] "ZERO_RESULTS"
```

Checking the status_code for success would be useful, returning a helpful message otherwise. When deployed within a `shiny` app, errors don't always float to the top the way one might hope.

**Comment by SymbolixAU** [comment]
Do you have an example of a zero-status query I can use to test?

Thanks for your other suggestions too; I won't be able to work on them until next week though. Feel free to submit a pull request if you want to implement them.

**Comment by SymbolixAU** [comment]
I've pushed a commit that adds checks around `curl::curl()`, and for a valid internet connection. Please check the `fun_download_data` function (in googleway-package.R). Is this what you had in mind?

**Comment by SymbolixAU** [comment]
see issue #9 for `zero_results`

**Comment by jonocarroll** [comment]
`curl` call looks a lot safer now, looks good. Cheers.

**Comment by SymbolixAU** [comment]
Good suggestion; see #14  👍
