### ISSUE TITLE
Marker clustering doesn't seem to work

### ISSUE THREAD

**Issue by gillesgerlo** [SymbolixAU/googleway#131]
Hi there,

Love the package, but can't seem to get the clustering to work. There doesn't seem to be a difference when I set cluster = T. Any help much appreciated!

google_map(data = tram_stops, key = key) %>%
  add_markers(lat = "stop_lat", lon = "stop_lon", info_window = "stop_name", cluster = TRUE)

**Comment by SymbolixAU** [comment]
@gillesgerlo thanks for finding this; I see the error too and will try to fix it

**Comment by SymbolixAU** [comment]
It seems the location of the 'images' got moved when Google transferred their Maps stuff to github, but they didn't update their docs. There are many issues about this online. 

For googleway I need to either store the images locally and reference them, or find a 'stable' online repo of the images.

**Comment by gillesgerlo** [comment]
Thanks for looking into it :)

**Comment by SymbolixAU** [comment]
@gillesgerlo - I've just pushed a commit that I think solves the issue. It was actually nothing to do with images - I hadn't accounted for a `setTimeout` call I added in the last update correctly.

**Comment by SymbolixAU** [comment]
Could you let me know if this works for you? 

You can install the dev version with

```
devtools::install_github("SymbolixAU/googleway")
```

**Comment by gillesgerlo** [comment]
Works like a charm, thanks a lot!
