### ISSUE TITLE
split view - suggestion for fullscreen_control

### ISSUE THREAD

**Issue by nbarsch** [SymbolixAU/googleway#138]
As a suggestion, the new split_view="pano" functionality of googleway in shiny (which is awesome) would be even better with fullscreen_control=TRUE, to create a fullscreen option for the user to make the map side or the interactive streetview side full screen.

**Comment by SymbolixAU** [comment]
You should se the 'full screen control' button on the map and streetview by default. It's the small box in the top right corner

![screen shot 2018-02-27 at 8 24 22 am](https://user-images.githubusercontent.com/18344164/36696216-aae256e8-1b97-11e8-8815-d149930beb66.png)

is this what you had in mind?

**Comment by SymbolixAU** [comment]
@nbarsch is the 'full screen control' button the solution to this?
