### ISSUE TITLE
Error when deploying google_map_update on shinyapps.io

### ISSUE THREAD

**Issue by gillesgerlo** [SymbolixAU/googleway#143]
I've run into a strange error when using the google_map_update function in a shinyapps.io app:
https://synaptiv.shinyapps.io/Road_Density/

Upon initialisation the map renders fine, based on the chunk below:
google_map(data = map) %>%
          add_heatmap(data = map, lat = 'lat', lon = 'lon', weight = 'nbr_journeys',
                      option_radius = input$heatmapRadius, legend = T, 
                      legend_options = list(title = 'Number of journeys'))

Refreshing the map using the refresh button on the left or the radius slider triggers an update to the map:
google_map_update(map_id = 'densityHeatmap') %>%
        update_heatmap(data = map, lat = 'lat', lon = 'lon', weight = 'nbr_journeys',
                       option_radius = input$heatmapRadius, legend = T, 
                       legend_options = list(title = 'Number of journeys'), update_map_view = F)

This is when the tool stops working, with the following error appearing in the console:
![image](https://user-images.githubusercontent.com/31394909/36735547-64298b36-1bce-11e8-9c57-ca185abaefe9.png)
Clicking on the error links to this bit of source code:
![image](https://user-images.githubusercontent.com/31394909/36735706-adf4f6c4-1bce-11e8-85c3-c8772512fd9e.png)

The same error appears when running the app locally, however afterwards the app updates as expected. For some reason this doesn't happen on the shinyapps version... I'm not much of a JavaScript expert so any help in understanding this error would be greatly appreciated!

**Comment by gillesgerlo** [comment]
Ok I just realised what I did wrong. I was using the google_map_update function within renderGoogle_map, but it should've been within an observeEvent instead. Sorry about that! Feel free to delete this issue :)

**Comment by SymbolixAU** [comment]
@gillesgerlo - that's a very cool app. And glad you found the solution. 

Are you aware the legend disappears when you change city?

**Comment by gillesgerlo** [comment]
Thanks!

Yeah I was just looking into that actually. Haven't been able to pinpoint
the problem exactly. Might reach out again if it persists. Have you seen
similar behaviour before?

**Comment by SymbolixAU** [comment]
I have not seen it before. But if you can't find a solution feel free to ask!
