### ISSUE TITLE
google_geocode function returns NULL occasionally when run inside the loop

### ISSUE THREAD

**Issue by Alekhb** [SymbolixAU/googleway#146]
Hi, I have a list of 1502 addresses. I want the latitude and longitude of all the address. When i am running each iteration individually it doesn't return NULL. When I am running the code inside the loop, the google_geocode function returns NULL and the loop stops. Why is this happening?

```
for (i in 1:nrow(petco)) {
  address1 <- paste0(petco$AddressLine1[i]," ",petco$AddressLine2[i])
  res <- google_geocode(address = address1,key = api_key)
  latitude <- res$results$geometry$location[1,1]
  longitude <- res$results$geometry$location[1,2]
  store_number <- petco$StoreNumber[i]
  df <- as.data.frame(cbind(store_number, latitude,longitude))
  store_petco_details <- rbind(store_petco_details,df)
  Sys.sleep(0.6)
}
```

**Comment by SymbolixAU** [comment]
@Alekhb  You could try implementing the solution [as described here](https://stackoverflow.com/q/44486388/5977215).

**Comment by SymbolixAU** [comment]
Closing as this is not an issue with `googleway` itself; the functions are working as expected. It's more likely to do with the API response.
