### ISSUE TITLE
Number of reviews with google_place_details

### ISSUE THREAD

**Issue by mtmx** [SymbolixAU/googleway#147]
Hello, I use your package to access informations about places.
google_place_details returns global rating for a place (i.e. mean of all the user ratings) but unfortunately not the number of user ratings.
[Only five reviews ](https://developers.google.com/maps/documentation/javascript/places#place_details_responses) are retrieved for a place, and it seems this limit can't be exceeded with a regular api key.

Scraping google maps pages of places (where the number of reviews is displayed) is obviously not an option.
Is there any chance this information could be available ?
Thanks.

**Comment by SymbolixAU** [comment]
`googleway` will only return what the Google API returns. So if that information is not available through the API then I can't make it available. 

Is there a specific field / result in Google's API that I am not returning?

**Comment by mtmx** [comment]
No, every useful field is returned by googe_place_details.
Sorry for bothering you.
