### ISSUE TITLE
Error in add_heatmap 

### ISSUE THREAD

**Issue by samistat08** [SymbolixAU/googleway#149]
I get the following error when I want to add heatmap to a google map using googleway package. 
```
Error: Must supply `z` attribute
```
The crazy part is that , it sometimes work and sometimes not. Any help would be appreciated.

**Comment by SymbolixAU** [comment]
That's not an error message from `googleway`, perhaps you have another library loaded with the same function name?

**Comment by SymbolixAU** [comment]
perhaps `plotly::add_heatmap` ? That requires a `z` argument.
