### ISSUE TITLE
There was an error downloading results

### ISSUE THREAD

**Issue by JohnnyxB** [SymbolixAU/googleway#151]
Hello SymbolixAU,

Running the code:
`google_geocode("BW PLUS HOTEL DARMSTADT	DARMSTADT	Germany", key = key, simplify = FALSE)`

I get the error in the heading and an URL to check:
`https://maps.googleapis.com/maps/api/geocode/json?&address=BW+PLUS+HOTEL+DARMSTADT	DARMSTADT	Germany&bounds=&key=`

This URL works if I put it in a browser.

Is this a bug? Can you help to solve it?

Thanks in advance.

**Comment by SymbolixAU** [comment]
@JohnnyxB 

Unfortunately I can't reproduce the error

```

library(googleway)
set_key("my_key")

res <- google_geocode("BW PLUS HOTEL DARMSTADT DARMSTADT Germany", simplify = FALSE)

res[1:20]

# [1] "{"                                                         
# [2] "   \"results\" : ["                                        
# [3] "      {"                                                   
# [4] "         \"address_components\" : ["                       
# [5] "            {"                                             
# [6] "               \"long_name\" : \"31\","                    
# [7] "               \"short_name\" : \"31\","                   
# [8] "               \"types\" : [ \"street_number\" ]"          
# [9] "            },"                                            
# [10] "            {"                                             
# [11] "               \"long_name\" : \"Grafenstraße\","          
# [12] "               \"short_name\" : \"Grafenstraße\","         
# [13] "               \"types\" : [ \"route\" ]"                  
# [14] "            },"                                            
# [15] "            {"                                             
# [16] "               \"long_name\" : \"Darmstadt\","             
# [17] "               \"short_name\" : \"Darmstadt\","            
# [18] "               \"types\" : [ \"locality\", \"political\" ]"
# [19] "            },"                                            
# [20] "            {"
```


[this is the line of code](https://github.com/SymbolixAU/googleway/blob/master/R/googleway-package.R#L159) which generates the warning. 
What happens if you try and run these lines manually:

```
con <- curl::curl(map_url)
out <- readLines(con)
close(con)
```

Using your url above as the `map_url` ?

**Comment by JohnnyxB** [comment]
Hello SymbolixAU,

if I run the code I get the following error:
```
map_url <- "https://maps.googleapis.com/maps/api/geocode/json?&address=BW+PLUS+HOTEL+DARMSTADT	DARMSTADT	Germany&bounds=&key="
con <- curl::curl(map_url)
out <- readLines(con)
Error in readLines(con) : HTTP error 400.
close(con)
```

May it be because I am working in a company network? I hast worked until a week ago...

Thanks for your help!

**Comment by SymbolixAU** [comment]
Is this the same error as you saw in [your other issue](https://github.com/SymbolixAU/googleway/issues/66) ?

**Comment by JohnnyxB** [comment]
No, the error looked different previously...

But I have just updated the packge and it works now!

Thank you. Should I close the issue?

**Comment by SymbolixAU** [comment]
yes, please close. Glad it's sorted for you.
