### ISSUE TITLE
update_map_view=F for add_KML()

### ISSUE THREAD

**Issue by mosscoder** [SymbolixAU/googleway#161]
Request option to not update the map view for add_KML(). This will allow for a better experience when viewing a time series of KMLs.

**Comment by SymbolixAU** [comment]
did you also send me an email with this request?

**Comment by SymbolixAU** [comment]
Also, the `kml` layer doesn't update update the map bounds (from within my javascript function). I'll have to look into whether this is something I can control through Google Maps or not.

**Comment by mosscoder** [comment]
Yes, I’m the same person that emailed you. Thanks for the great work!

**Comment by SymbolixAU** [comment]
possible solution: https://stackoverflow.com/a/8189221/5977215

**Comment by SymbolixAU** [comment]
@mosscoder  if you update your version from the `overlay` branch you'll see the `update_map_view` argument for `add_kml()`. Could you let me know if this works for you?

**Comment by mosscoder** [comment]
This update works perfectly for me, thank you!
