### ISSUE TITLE
Polylines to static image/tile

### ISSUE THREAD

**Issue by gillesgerlo** [SymbolixAU/googleway#165]
Hi,
This might be a long shot, but is there a way to convert a plot of polylines to an image or static tile for faster rendering? I'm trying to plot colored roads in an area, but the sheer amount of different polylines makes rendering the map really slow. Any suggestions much appreciated!

**Comment by SymbolixAU** [comment]
You could try using a [kml](https://developers.google.com/kml/documentation/) layer or an [overlay](https://developers.google.com/maps/documentation/javascript/examples/overlay-simple). I don't know how well these will work on your data, however. 

Or you could experiment with WebGL ([an example of my own experiments](https://twitter.com/symbolixAU/status/993765640904130560)), which shows some promise. But I haven't got far with this yet.

**Comment by gillesgerlo** [comment]
Thanks for your reply, I'll definitely investigate. Your WebGL example in particular is pretty much what I'm trying to achieve, but with polylines rather than circles. Would you share the code for this example? 
I do not have a developer background, so any solution where I can somehow convert my current (dynamic) polylines plot to a static version in R would be amazing!

**Comment by SymbolixAU** [comment]
I'm not sharing the code at the moment because it's very experimental and requires combining 2 javascript libraries and another R library into another package. And I don't want anyone using it for any meaningful / production work because it will change and break regularly during this initial development stage.

**Comment by gillesgerlo** [comment]
Fair enough, sounds like that'd be out of my comfort zone anyway. Will experiment with KML instead, thanks

**Comment by gillesgerlo** [comment]
So I've found a solution by creating kml files using the maptools::kmlLines function. I think plotting this file using add_kml will be straightforward, however it seems to only support public urls at the moment. I assume plotting local KML files is still in development as per #76 ?

**Comment by SymbolixAU** [comment]
You're right, it's on my to-do list, however, I'm not sure it's possible to plot local kml files. The Google reference documents suggest it has to be pubicly available

https://developers.google.com/maps/documentation/javascript/kmllayer#overview
>These data formats are displayed on a map using a KmlLayer object, whose constructor takes the URL of a publicly accessible KML or GeoRSS file.

**Comment by gillesgerlo** [comment]
Yes I fear that will be the case. And I suppose the same problem will exist for overlays...
I might have to move to leaflet on this. In any case thanks for the help!

**Comment by SymbolixAU** [comment]
`mapview` (and therefore I assume `leaflet` too) has a `canvas = TRUE` option https://twitter.com/TimSalabim3/status/989128349036564481 which is good for plotting large amounts of data.

**Comment by gillesgerlo** [comment]
Thanks a lot! I'll keep an eye out for the work you're doing with WebGL ;)

**Comment by SymbolixAU** [comment]
@gillesgerlo my latest packge, [mapdeck](https://github.com/symbolixau/mapdeck) may be of interest. Currently in dev, but I've submitted to CRAN so hoping it will be accepted soon.

**Comment by gillesgerlo** [comment]
Thanks, will check it out!
