### ISSUE TITLE
variable to define column in `data`

### ISSUE THREAD

**Issue by SymbolixAU** [SymbolixAU/googleway#168]
By design using a variable as a column identifier doesn't work. Maybe it should in the next release?

```
map_key <- read.dcf("~/Documents/.googleAPI", fields = "GOOGLE_MAP_KEY")
df <- melbourne[1:3,]
df$rand <- as.character(rnorm(nrow(df)))
iw <- "rand"
google_map(key = map_key) %>%
  add_polygons(
    data = df
    , polyline = "polyline"
    , info_window = iw
    , id = "polygonId"
)
```

So if the variable refers to a column in the `data.frame` it's recognised as such. 

related #182

**Comment by SymbolixAU** [comment]
Yes it would. However, I'm going to re-design the whole library in a few weeks, so it might take a while to get working / right.

**Comment by tradeli** [comment]
Is there a way to circumvent this behavior ? Using some form of quasiquotation or quick workarround to make it support variables?

**Comment by SymbolixAU** [comment]
I've made a "variables" branch where you can test out this functionality

```r
devtools::install_github("SymbolixAU/googleway", ref = "variables"
```

This is now working for me

```r
library(googleway)

set_key( read.dcf("~/.googleAPI", fields = "GOOGLE_MAP_KEY"))

col <- "stop_name"
myPoly <- "polyline"
polyColour <- "SA2_NAME"

google_map() %>%
  add_circles(
    data = tram_stops
    , fill_colour = col
  ) %>%
  add_markers(
    data = tram_stops
  ) %>%
  add_polygons(
    data = melbourne
    , polyline = myPoly
    , fill_colour = polyColour
  )
library(googleway)

set_key("GOOGLE_MAP_KEY")

col <- "stop_name"
myPoly <- "polyline"
polyColour <- "SA2_NAME"

google_map() %>%
  add_circles(
    data = tram_stops
    , fill_colour = col
  ) %>%
  add_markers(
    data = tram_stops
  ) %>%
  add_polygons(
    data = melbourne
    , polyline = myPoly
    , fill_colour = polyColour
  )
```

Please let me know if you have any issues.

**Comment by tradeli** [comment]
It works! Thank you very much!

**Comment by dcooley** [comment]
got completely sidetracked so never got around to redesigning this. However, I've now merged the variables branch into master.
