### ISSUE TITLE
google_map function not working on Microsoft R Open v3.5.0

### ISSUE THREAD

**Issue by gusmclennan** [SymbolixAU/googleway#169]
Hey there.  I am wanting to use the google_map function to generate Google Street Map views within a Shiny application.  However, I couldn't get even your example code for google_map to work.  I have since determined that the problem is the version of R, as I recently migrated to Microsoft R Open (R-3.5.0).  I got a colleague who has not migrated yet to test, and the sample code worked fine for him.  I was wondering when (or if) the google_way package is likely to be certified for Microsoft R.  Here is the code I was using (with my own Google API key, which I know is valid as I have been using it for geocoding functions).

```
library(shinydashboard)
library(googleway)

ui <- fluidPage(google_mapOutput(outputId = "map"))

server <- function(input, output, session){
    
    api_key <- "my_app_code"
    
    output$map <- renderGoogle_map({
        google_map(location = c(-37.80967, 144.9699), key = api_key)
    })
}

shinyApp(ui, server)
```

**Comment by SymbolixAU** [comment]
> when (or if) the google_way package is likely to be certified for Microsoft R.

I'm not sure I can answer that, as I don't know what Microsoft does which prevents packages from running. 

Do you receive any error messages?

**Comment by gusmclennan** [comment]
No, unfortunately not.  Code runs fine, but when the Shiny app launches, the box within shinydashboard with the renderGoogle_map function doesn't render anything.  This is the first potential issue I have seen with Microsoft R, but it has only been a day since I migrated...Is there any option for verbose logging or something like that, that could be called to try and troubleshoot this further...?

**Comment by SymbolixAU** [comment]
I don't have any verbose options within `googleway`.

Are you saying you can plot a map from within RStudio/R (i.e. not using shiny) just with `google_map(key = api_key)`?

I also have no issue running your example shiny (although you need to replace `library(shinydashboard)` with `library(shiny)` ).

**Comment by gusmclennan** [comment]
I have tried running the google_map function within R Studio as well, and don't get anything plotted in the Viewer panel within R Studio.  I am going to get a colleague who also migrated to MS R to see if he has the same experience running the code.

**Comment by SymbolixAU** [comment]
which versions of RStudio and `googleway`?

**Comment by gusmclennan** [comment]
OK - Just checked with my colleague who is also running Microsoft R, and he was able to run the google_map function in R Studio...so this issue seems isolated to my R environment.  He is running R Studio Version 1.0.153 and latest version of googleway.  Apologies, should I close this issue at this time...?

**Comment by SymbolixAU** [comment]
It's ok; it's often helpful to explore all avenues when debugging these kinds of things. 

If you discover the issue & solution would you mind posting back here the answer?
