### ISSUE TITLE
API Key Required?

### ISSUE THREAD

**Issue by jzadra** [SymbolixAU/googleway#171]
I was just curious why the API key is required, since `ggmap::geocode()` works without an API key up to a certain number of requests. As a low volume, occasional user who doesn't need beyond the free limit it would be great not to have to enter billing info and get a personal API key.

**Comment by SymbolixAU** [comment]
Please see #27 

In summary, Google stipulates in their documents you need a key. However, you can use an empty one for backwards compatibility. I won't be surprised in the future if they remove this and mandate a key for all users though.

**Comment by jzadra** [comment]
Thanks.
