### ISSUE TITLE
deck.gl

### ISSUE THREAD

**Issue by SymbolixAU** [SymbolixAU/googleway#172]
https://github.com/uber/deck.gl/pull/2179

**Comment by SymbolixAU** [comment]
update: https://github.com/uber/deck.gl/pull/2900

**Comment by dcooley** [comment]
and: https://github.com/uber/deck.gl/blob/master/docs/api-reference/google-maps/google-maps-overlay.md

**Comment by dcooley** [comment]
implementing in mapdeck: https://github.com/SymbolixAU/mapdeck/issues/162
