### ISSUE TITLE
Geolocation

### ISSUE THREAD

**Issue by SymbolixAU** [SymbolixAU/googleway#173]
https://developers.google.com/maps/documentation/javascript/geolocation

**Comment by SymbolixAU** [comment]
To observe a user's location

```r
observeEvent({ input$map_id_geolocation }, { } )
```

**Comment by tnelsen** [comment]
I am not able to access the geolocation in this way. I am getting "geolocation.js:23 Uncaught ReferenceError: map_id is not defined at geolocation.js:23"  in my browser developer tools. A minimal example is below. I can print from map click, marker drag, etc. but am getting NULL if I try to return the geolocation. Thanks in advance. 

#########
library(googleway)
library(shiny)

readRenviron('../.Renviron')

ui <- fluidPage(
	google_mapOutput("map")
)

server <- function(input, output, session){
	output$map <- renderGoogle_map({
		google_map(key = Sys.getenv("MAPS_API_KEY"), location = c(38.54, -121.78),
							 zoom = 8, search_box = TRUE, geolocation = TRUE,
							 width = '100%', height = '100%'
		) %>%
			add_markers(data = data.frame(lat = 38.54, lon = -121.78),
									draggable = TRUE, update_map_view = FALSE)})
	
	observeEvent(input$map_marker_drag, {
		print(input$map_marker_drag)
	})
	
	observeEvent(input$map_map_click, {
		print(input$map_map_click)
	})
	
	#https://github.com/SymbolixAU/googleway/issues/173
	observeEvent(input$map_geolocation,{
		print(input$map_geolocation)
	})
}

shinyApp(ui, server)

**Comment by dcooley** [comment]
Are you opening this in a browswer, and do you have it set to "allow location" ?

**Comment by tnelsen** [comment]
I am opening it in a Google Chrome browser and I get a pop-up asking if I want to allow it to access my location. I click yes but still nothing happens.

**Comment by dcooley** [comment]
oh I see, it might need a 'wait until map is ready' before calling the `add_geolocation()`... I'll look into it.

**Comment by dcooley** [comment]
Ok this is not quite as straight forward, and I don't know if this worked before, but it's certainly not working now. 

The `add_geolocation()` function in `js` needs to 

- [x] 'observe' the geolocation result
- [ ] send back to shiny server

**Comment by dcooley** [comment]
ok I think it now works

```r
shinyApp(ui, server)

Listening on http://127.0.0.1:5590
$lat
[1] -37.8898

$lon
[1] 144.9904

$accuracy
[1] 20

$altitude
NULL

$altitudeAccuracy
NULL

$heading
NULL

$speed
NULL

$timestamp
[1] 1.608248e+12

$randomValue
[1] 0.9922257
```

**Comment by tnelsen** [comment]
Thanks for this fix! It seems to be working now.
