### ISSUE TITLE
Error downloading results

### ISSUE THREAD

**Issue by abbykaynig** [SymbolixAU/googleway#188]
I received the following error: 

 Error in value[[3L]](cond) : 
  There was an error downloading results. Please manually check the following URL is valid by entering it into a browswer. If valid, please file a bug report citing this URL (note: your API key has been removed, so you will need to add that back in) 

https://maps.googleapis.com/maps/api/distancematrix/json?&origins=41.798958,-78.442315&destinations=42.111371,-80.079539&alternatives=false&units=imperial&mode=driving&key=

When I followed the URL manually, however, I did not receive an error.

**Comment by SymbolixAU** [comment]
Hi @abbykaynig  Please see [this issue](https://github.com/SymbolixAU/googleway/issues/187) and let me know if the solutions work.

**Comment by SymbolixAU** [comment]
@abbykaynig are you still having an issue?
