### ISSUE TITLE
Error with add_heatmap

### ISSUE THREAD

**Issue by tradeli** [SymbolixAU/googleway#189]
EDIT: I'm running R3.5.1, RStudio 1.1.4, Windows 10, Google Chrome 71

When I try to plot markers, it works just fine. But if I try to plot a heat map, it gives the error in the image below and nothing is plotted on the map:

![error_maps](https://user-images.githubusercontent.com/8575811/50445552-ac777e00-08f6-11e9-9be4-fb93f8b5477e.png)

No matter how many times I try to press F5 or forced reload, it still gives the same problem.

The code I'm using is this:

```
ui <- fluidPage(google_mapOutput(outputId = "map"))


server <- function(input, output) {
  map_key = MY_KEY#Here I replace the MY_KEY with my actual google maps key
  
  output$map <- renderGoogle_map({
    tabelaDadosCidadesCandidatas = data.table(
      latitude = c(-27.68970, -9.18564, -16.46420),
      longitude = c(-51.1271, -43.0494, -49.9617)
    )
    
    add_heatmap(
      map = google_map(
        width = '100%',
        height = '100%',
        fullscreen_control = TRUE,
        street_view_control = FALSE,
        map_type_control = FALSE,
        search_box = FALSE,
        key = map_key
      ),
      data = tabelaDadosCidadesCandidatas,
      lat = "latitude",
      lon = "longitude",
      option_radius = 0.001
    )
  })
  
}

shinyApp(ui = ui, server = server)
```

**Comment by SymbolixAU** [comment]
I've just pushed a commit to the dev version to check the charts library is loaded in a shiny environment. Could you install it and let me know if it works for you?



```r
devtools::install_github("SymbolixAU/googleway")
```
Then you should see (I changed the `option_radius` to `10` in this example)

```r
shinyApp(ui = ui, server = server)
```


![screen shot 2018-12-27 at 11 29 30 am](https://user-images.githubusercontent.com/18344164/50460569-5a545c80-09cb-11e9-8feb-af7b74b68bf8.png)

**Comment by tradeli** [comment]
It worked!!!!!!!!!!!!!
Thank you very much sir!
