### ISSUE TITLE
add_heatmap does not show negative "weight" values with gradient (only single color rectangles)

### ISSUE THREAD

**Issue by sayac007** [SymbolixAU/googleway#191]
Dear All,

at least in my RStudio, google_map along with add_heatmap does not show negative "weight" values as a gradient color. Positive values are displayed correctly. If I divide positive and negative values in separate columns and use "add_heatmap" twice (once for positive values and once for negative multiplied by -1) with different "option_gradient" palettes, it works sometimes but in some cases the new gradient overwrites the old one. Unfortunately, "add_heatmap" doesn't work with missing values (NA).

Data - just 3 columns (lats, longs, and temperature).

Code: 

```r
map <- google_map(key = key, data = data) %>%
    add_heatmap(lat = "lats", lon = "lons", weight = "temp",
                option_radius = 0.3, option_gradient = option_gradient, option_opacity = 1, legend = TRUE)
```

Also, sometimes legend is displayed and sometimes not - not stable yet?

<img width="351" alt="rplot" src="https://user-images.githubusercontent.com/14997159/52558748-a6305900-2df3-11e9-8dc9-01aa0b3d053a.png">

**Comment by SymbolixAU** [comment]
Can you provide some data I can use to replicate your issue please?

**Comment by sayac007** [comment]
https://docs.google.com/spreadsheets/d/1zR-rPe_ymcz2mtRKCQsFqbU7wVl8w4lQ4oetq0mfNAQ/edit?usp=sharing

**Comment by SymbolixAU** [comment]
I'm not sure it makes sense to have negative weights. The 'weight' in this context means how much each lon/lat coordinates counts towards the intensity (colour). If the coordinates within a specified location all sum to < -1, what colour **should** that be?

**Comment by sayac007** [comment]
I agree, it is not the best option. I think a good solution would be to enable multiple gradients like it is already the case e.g. for fill color and stroke color where you can visualize two attributes in the same map. It would be great to have the same option/possibility for the "option_gradient" - if would be cool to be able to visualize at least two measures/metrics independently in the same graph. E.g. you want to show income for some states and education for others. It would also solve my problem (as a workaround) because I will be able to show negative temperatures in one gradient and positive in another. But would be a lot of work for you of course so regard it just as a suggestion. In any case, thanks a lot for the extremely useful package you've developed!

**Comment by SymbolixAU** [comment]
you can add two heatmap layers, and specify the colours in the `options_gradient` argument

**Comment by SymbolixAU** [comment]
I have a couple of examples of changing the colours [here](https://github.com/SymbolixAU/googleway/blob/master/tests/manual_tests.R#L260) and [here](https://github.com/SymbolixAU/googleway/blob/master/tests/manual_tests.R#L528)

**Comment by sayac007** [comment]
Can you please give me an example how to add two heatmap layers? Thanks a lot in advance!

**Comment by SymbolixAU** [comment]
```r

library(googleway)

google_map() %>%
  add_heatmap(
    data = tram_stops[1:25,]
  ) %>%
  add_heatmap(
    data = tram_stops[26:51,]
    , option_gradient = c("white","blue","orange")
  )

```

![screen shot 2019-02-28 at 7 39 05 pm](https://user-images.githubusercontent.com/18344164/53552909-8d17fe00-3b90-11e9-937b-83a3b793fef8.png)

**Comment by sayac007** [comment]
Thanks a lot!
