### ISSUE TITLE
htmlwidgets not loading

### ISSUE THREAD

**Issue by vawdreyjack** [SymbolixAU/googleway#194]
After migrating to a new machine, I've been unsuccessful in getting my google_map objects to render. An htmlwidget appears when I run even a simple version of the google_map function, but the htmlwidget is blank. I'm not getting any errors that I can tell. 

Still new to R, so I appreciate your help :). 

![Screenshot (2)](https://user-images.githubusercontent.com/49199257/55408495-5598ca80-551d-11e9-8852-9c12d79b0091.png)

**Comment by SymbolixAU** [comment]
did it work on the old machine?

**Comment by vawdreyjack** [comment]
Yes, and it still does. I just moved to a machine with a little more power, but for some reason the htmlwidgets don't want to display. The session info between the two machines is identical.

**Comment by SymbolixAU** [comment]
what code are you using to plot the map? Have you set the key correctly?

**Comment by vawdreyjack** [comment]
Even the simplest code won't show a map. A
![Screenshot (4)](https://user-images.githubusercontent.com/49199257/55451508-6c2c3980-5590-11e9-98aa-905537306266.png)
 blank htmlwidget appears, like below.

**Comment by SymbolixAU** [comment]
what happens if you run it directly in the console, not in a markdown document?

**Comment by vawdreyjack** [comment]
I tried that. It activates the Viewer window as if a map should appear there, but the same thing happens: blank 😬

**Comment by SymbolixAU** [comment]
Can you then press 'open in browser', then check the javascript console in the browser (in Chrome you press Ctrl (Cmd) + Shift + C ), to see if there are any errors

**Comment by vawdreyjack** [comment]
Okay, so that made it so I could see the map in the browser, but it didn't look like there were any errors. Very strange that I'm not able to see it in RStudio.

**Comment by SymbolixAU** [comment]
Are you still having this issue?

**Comment by vawdreyjack** [comment]
I finished the project where I was using the library, but was never able to
solve the issue.

**Comment by krlmlr** [comment]
I'm seeing a very similar problem. Instead of a blank map, the output is:

![Screenshot from 2020-06-04 16-39-26](https://user-images.githubusercontent.com/1741643/83770956-ff279e80-a681-11ea-9477-44c5bb6e7d05.png)

In the console I'm seeing:

> Google Maps JavaScript API error: ApiNotActivatedMapError
> https://developers.google.com/maps/documentation/javascript/error-messages#api-not-activated-map-error

We can use the same key for geocoding via `google_geocode()`, though.

**Comment by dcooley** [comment]
@krlmlr the "not activated" suggests the key is not set up for use for maps. Can you check you've enabled the key for the Maps API also?

**Comment by krlmlr** [comment]
We weren't able to find the button to toggle it yet. I guess we need to take a closer look at https://developers.google.com/maps/documentation/javascript/get-api-key#restrict_key?

**Comment by dcooley** [comment]
If you haven't already set any restrictions then that's probably not the issue. (But they will be useful if / when you deploy anything online to help keep your key more secure)

perhaps this page will help solve your API key issues: https://developers.google.com/maps/documentation/javascript/tutorial#api-key-billing-errors
