### ISSUE TITLE
Suggestion to return map center lat/lon for bounds_changed events

### ISSUE THREAD

**Issue by davedgd** [SymbolixAU/googleway#204]
This is a small feature request/enhancement, but it would be helpful to return the map center lat/lon when using bounds_changed in addition to the northEast/southWest coordinates. This is particularly relevant when using the search box (or manual) method to update the map: specifically, it's helpful to know the current coordinates on these dynamic changes (e.g., to then use the new coordinates in Shiny for some purpose). Right now, it takes a bit of code in R to get this info (see below). Instead, I would suggest the following very minor change in [map_events.js](https://github.com/SymbolixAU/googleway/blob/master/inst/htmlwidgets/lib/map/map_events.js) (also below).

On a related note, it may be good to explain this functionality in the vignette near ["Clicking on the map"](https://cran.r-project.org/web/packages/googleway/vignettes/googleway-vignette.html#clicking-on-the-map). Specifically, a quick example along the lines of "Getting the current coordinates" might be helpful, since a key value of googleway is the interactive maps (as opposed to [ggmap](https://cran.r-project.org/web/packages/ggmap/index.html) for example, which is designed for static use).

Current R approach:

```R
#Observe changes to the map and calculate current map center
observeEvent(input$myMap_bounds_changed, {
    print(input$myMap_bounds_changed)
    
    latLon = data.frame(
        lat = mean(c(input$myMap_bounds_changed$southWestLat, input$myMap_bounds_changed$northEastLat)),
        lng = mean(c(input$myMap_bounds_changed$southWestLon, input$myMap_bounds_changed$northEastLon))
    )
    
    cat("Approximate map center:\n\n")
    print(latLon)
    
})
```

Output:

```R
$id
[1] "myMap"

$northEastLat
[1] -37.46614

$northEastLon
[1] 145.5499

$southWestLat
[1] -37.90086

$southWestLon
[1] 144.6101

$randomValue
[1] 0.6924636

Approximate map center:

       lat    lng
1 -37.6835 145.08
```

Suggested change to googleway map_events.js:

```javascript

function bounds_changed(map_id, mapObject, mapInfo) {

    //'use strict';
  if (!HTMLWidgets.shinyMode) {
    return;
  }

  google.maps.event.addListener(mapObject, 'bounds_changed', function (event) {
    var eventInfo = $.extend(
      {
        id: map_id,
        northEastLat: mapObject.getBounds().getNorthEast().lat(),
        northEastLon: mapObject.getBounds().getNorthEast().lng(),
        southWestLat: mapObject.getBounds().getSouthWest().lat(),
        southWestLon: mapObject.getBounds().getSouthWest().lng(),
        centerLat: mapObject.getCenter().lat(), // add center lat
        centerLon: mapObject.getCenter().lng(), // add center lon
        randomValue: Math.random()
      },
      mapInfo
    ),
    event_return_type = window.googleway.params[1].event_return_type;
    eventInfo = event_return_type === "list" ? eventInfo : JSON.stringify(eventInfo);
    Shiny.onInputChange(map_id + "_bounds_changed", eventInfo);
  });
}
```

**Comment by SymbolixAU** [comment]
Thanks for the suggestion and worked example (always very helpful!). 

I've made the change to `map_event.js` - let me know if this works for you.

**Comment by davedgd** [comment]
Thank you for the quick reply! I have some students who will appreciate this being streamlined. =)

**Comment by SymbolixAU** [comment]
No problem. Might also be worth looking at my other mapping library [mapdeck](https://github.com/SymbolixAU/mapdeck), which uses WebGL (through Uber's Deck.gl). It's much quicker and can handle much more data (millions of points)

**Comment by davedgd** [comment]
Thank you for the suggestion -- I'll definitely check it out!
