### ISSUE TITLE
Map not reacting in shiny

### ISSUE THREAD

**Issue by mmoralesIG** [SymbolixAU/googleway#206]
Hi, 
I have a sidebar in a shiny platform. One tab contains my google_map, which shows markers reacting whenever I click on the map. The problem is when I go to a different tab, then I go back to the map one, and the map it's not reacting.
I think the output is not reloading or refreshing when I go back.

Is there a way that the map reload when I go to the tab? That is, is there a way to reload the google_mapOutput?

**Comment by dcooley** [comment]
Please provide a fully reproducible example.

**Comment by SymbolixAU** [comment]
please re-open with a reproducible example
