### ISSUE TITLE
Overlaying Raster Image ?

### ISSUE THREAD

**Issue by sail370** [SymbolixAU/googleway#209]
The raster can be converted to polygons and be added using add_polygons. But it takes long to overlay medium sized rasters on the map.

**Comment by SymbolixAU** [comment]
Is this a question?

**Comment by sail370** [comment]
yeah, what is the workaround to plot a raster using googleway ?

**Comment by SymbolixAU** [comment]
You might have more success with [mapdeck](https://github.com/SymbolixAU/mapdeck) - it's designed to handle much larger data
