### ISSUE TITLE
Error isFalse could not find function

### ISSUE THREAD

**Issue by nvelden** [SymbolixAU/googleway#210]
I get the following error when I deploy my Shiny app on my Digital Ocean Ubuntu 18.04.3 (LTS) x64
droplet:

Error in isFALSE(.auth$auth_active) : could not find function "isFALSE"
Warning: Error in error_check: could not find function "isFALSE"

Do I miss some kind of dependency? It is working fine when I deploy my app on shinyapps.io

**Comment by SymbolixAU** [comment]
Is this issue related to `googleway`, as I don't have a function in my library called `isFALSE`?

**Comment by nvelden** [comment]
It was caused by running an old R version that led to an error on the mapview package: 
https://github.com/r-spatial/mapview/issues/177

Sorry about that.
