### ISSUE TITLE
google search textbox cum selectizeinput

### ISSUE THREAD

**Issue by chrisvwn** [SymbolixAU/googleway#213]
Is it possible to either create a shiny equivalent of the google map search textbox or simulate the functionality of the google map search textbox with existing components? That is:
1. Creates dropdown of possible results of the typed in value
2. Update choices as the user types (maybe when the user stops typing for 1-2 sec then update choices to prevent too many queries?)
3. Can accept typed in value even if no matching values are found directly

I have tried to use `selectizeInput` and `dqshiny::autocomplete_input` but these do not allow the capture of text while typing - only by choosing a dropdown value. 

Some similar questions:
[https://stackoverflow.com/questions/53347495/r-shiny-map-search-input-box](https://stackoverflow.com/questions/53347495/r-shiny-map-search-input-box)

**Comment by SymbolixAU** [comment]
In theory this is what `googleway::google_place_auotcomplete()` is supposed to do. However, I've never quite got it working as it's supposed to. 

There's also this other question https://stackoverflow.com/questions/54848254/shinydashboard-google-places-autocomplete-invalidvalueerror-not-an-instance-o

But other than that I don't have a solution.

**Comment by chrisvwn** [comment]
Thanks for the response @SymbolixAU. This is indeed not a simple problem.

**Comment by chrisvwn** [comment]
@SymbolixAU Please see a possible solution to this issue, although it uses another package. I have tested it a little and it seems to work quite nicely.
[https://github.com/daqana/dqshiny/issues/7](https://github.com/daqana/dqshiny/issues/7)
