### ISSUE TITLE
googleway:::isUrl prevents use of local files

### ISSUE THREAD

**Issue by avsdev-cw** [SymbolixAU/googleway#214]
Current implementation:
```R
function (txt) 
grepl("(^http)|(^www)", txt)
```

Suggest adding `(^file)` to it

**Comment by SymbolixAU** [comment]
@avsdev-cw I've updated the package with your suggestion. Does it solve the task you were trying to do?

**Comment by avsdev-cw** [comment]
Yup, thanks!
