### ISSUE TITLE
Modularizing / multiple instances of `renderGoogle_map()` in Shiny

### ISSUE THREAD

**Issue by robbfitzsimmons** [SymbolixAU/googleway#217]
Thanks very much for the super-helpful package!

I'm attempting to collect multiple geocoded addresses with {googleway}; having a map visible is 
somewhat incidental to me as I'm really hoping to use the search bar with autocomplete for shiny inputs. I would ideally like three (or more) maps, each assigned to their own output, and to be able to use the [input$map_place_search](https://github.com/SymbolixAU/googleway/blob/master/inst/htmlwidgets/google_map.js#L353) functionality to drive output elsewhere in the app.

I'm able to instantiate three maps with different output identifiers on one page or several, but they seem to be writing to the same input slot, even under different names (see the `renderPrint`s below); once I have searched from all three, they are all referencing one (the most recent) searched address. (I've read the docs and source and don't see any way to set an inputId or otherwise namespace the map results.

I'm attaching below a .zip of the reprex flexdashboard I'm using (it's also pasted below, but Github tends to mangle Rmd formatting).
[reprex.Rmd.zip](https://github.com/SymbolixAU/googleway/files/4137008/reprex.Rmd.zip)

Is there any way to address this with the current package functionality? Thank you!

---
title: "Googleway Multiple Maps Reprex"
runtime: shiny
output:
  flexdashboard::flex_dashboard
---

```{r setup, echo=FALSE}
library(tidyverse)
library(googleway)
library(shiny)
library(sf)

Sys.setenv(GOOGLE_MAPS_KEY="")
```

Inputs {.sidebar data-width=250}
===============================

```{r}
shiny::renderPrint({input$map_location_1_place_search})
shiny::renderPrint({input$map_location_2_place_search})
shiny::renderPrint({input$map_location_3_place_search})
```

First Location
===============

```{r map_1}
output$map_location_1 <- googleway::renderGoogle_map(
  googleway::google_map(
    map_type_control = FALSE,
    street_view_control = FALSE,
    zoom_control = FALSE,
    fullscreen_control = FALSE,
    search_box = TRUE,
    event_return_type = "list",
    key = Sys.getenv("GOOGLE_MAPS_KEY")
  )
)

googleway::google_mapOutput("map_location_1", height = "100%", width = "100%")
```

Second Location 
===============

### Location 2

```{r map_2}
output$map_location_2 <- googleway::renderGoogle_map(
  googleway::google_map(
    map_type_control = FALSE,
    street_view_control = FALSE,
    zoom_control = FALSE,
    fullscreen_control = FALSE,
    search_box = TRUE,
    event_return_type = "list",
    key = Sys.getenv("GOOGLE_MAPS_KEY")
  )
)

googleway::google_mapOutput("map_location_2", height = "100%", width = "100%")
```

Third Location
==============

### Location 3

```{r map_3}
output$map_location_3 <- googleway::renderGoogle_map(
  googleway::google_map(
    map_type_control = FALSE,
    street_view_control = FALSE,
    zoom_control = FALSE,
    fullscreen_control = FALSE,
    search_box = TRUE,
    event_return_type = "list",
    key = Sys.getenv("GOOGLE_MAPS_KEY")
  )
)

googleway::google_mapOutput("map_location_3", height = "100%", width = "100%")
```

**Comment by SymbolixAU** [comment]
I assume the `tidyverse` isn't actually needed?

**Comment by robbfitzsimmons** [comment]
@SymbolixAU sorry, you're correct - bad habits, was stripping out a reprex from my own code.

In the interim, I've worked around this by simply limiting to one map / searchbox in the app and adding searches iteratively to a `shiny::reactiveValues()` list, so it works fine for the time being. Would be wonderful to use multiple maps in a single app, likely using a shiny `inputId` param. I'd love to be helpful in figuring out how to modularize, but haven't had a chance to look into the internals of your package.

Thanks again for the great work!

**Comment by SymbolixAU** [comment]
Glad you've got a work-around, but you're right, this should work for multiple map instances. 

I was away at RStudio::conf, then took some leave, so haven't looked at this until now. I'll see if I can see what's going on.

**Comment by SymbolixAU** [comment]
ok I might have found it. Can you try and install from this branch

```r
remotes::install_github("SymbolixAU/googleway", ref = "issue217")
```

and try again?

**Comment by robbfitzsimmons** [comment]
Nailed it! That works now, nice fix and thanks again.

I was at the conf too - consider this a placeholder offer to buy you a beer next year as a thank-you for this package and {mapdeck}.

**Comment by SymbolixAU** [comment]
ah cool - did we meet by any chance?

**Comment by robbfitzsimmons** [comment]
Don't think we met, unfortunately - I was lame and spent all my time outside the sessions on my laptop putting together an app for a customer on a deadline, which is where I hit this issue... thanks again, Dave!
