### ISSUE TITLE
add_markers cluster size

### ISSUE THREAD

**Issue by zeehasham** [SymbolixAU/googleway#224]
Hi,
Is it possible to pass minimum size of points in cluster as a parameter to add_markers function when cluster=TRUE? There are two benefits
1. We will get rid of small cluster sizes.
2. What I found is if you have two points with the same latitude/longitude then cluster will never show you pins and remains in the cluster form even with maximum zoom.
Thanks,
Zee

**Comment by dcooley** [comment]
Thanks for the suggestion @zeehasham . Yes I think this is possible given it's one of the available [options](https://github.com/SymbolixAU/googleway/blob/master/inst/htmlwidgets/lib/markers/markerclusterer.js#L43).

I've made a branch where I've had a go at starting this. Would you mind testing it for me and seeing if it does what you're expecting.

```r
remotes::install_github("SymbolixAU/googleway", ref = "issue224")
```

### Example


```r
library(googleway)
library(sf)                
library(sfheaders)  ## for converting LINESTRINGS to POINTS
library(mapdeck)   ## using the 'roads' data

set_key( secret::get_secret("googleway") )

sf <- mapdeck::roads
sf_pts <- sfheaders::sf_cast( sf, "POINT") 

sf_pts <- sf_pts[1:100, ]
```

The default clustering

```r
google_map() %>%
  add_markers(
    data = sf_pts
    , cluster = T
  )
```

![Screen Shot 2020-08-06 at 8 35 31 am](https://user-images.githubusercontent.com/8093396/89470862-1db03000-d7c0-11ea-8951-25354898611b.png)


And using `min_cluster_size = 5`

```
google_map() %>%
  add_markers(
    data = sf_pts
    , cluster = T
    , cluster_options = list(min_cluster_size = 5)
  )
```
![Screen Shot 2020-08-06 at 8 36 20 am](https://user-images.githubusercontent.com/8093396/89470986-5fd97180-d7c0-11ea-94b4-620319b6814c.png)

**Comment by zeehasham** [comment]
@dcooley Thanks Dave for the prompt response. I tested it and confirm that this works exactly as was required. Let me know when this features becomes a part of release.

**Comment by dcooley** [comment]
I've added all the options, updated the docs for `?add_markers` and merged into master branch. 

I'm not sure when I'll have an update on CRAN though. Could be a few weeks.
