### ISSUE TITLE
add_polygon legend=T Error

### ISSUE THREAD

**Issue by zeehasham** [SymbolixAU/googleway#225]
Hi,

I am getting Error in <-: invalid subscript type 'list' while using legend = T inside add_polygon function

```r
add_polygons(sf, fill_colour = "#00FF00", fill_opacity = 0.2, update_map_view = F, layer_id = 'polygons', legend = T)
```

Any advice would be really appreciated.

**Comment by dcooley** [comment]
closing as duplicate of - https://github.com/SymbolixAU/googleway/issues/184
