### ISSUE TITLE
Request: Google maps "typical" traffic

### ISSUE THREAD

**Issue by chrislim5** [SymbolixAU/googleway#229]
On Google Maps there is an option to show the "typical" traffic for a certain day and time instead of the live traffic layer. Would this be possible to incorporate as an option in googleway::add_traffic() ?

**Comment by dcooley** [comment]
Do you have a link to the documentation for the 'typical' layer?

**Comment by chrislim5** [comment]
Sorry, I may have been mistaken. The "typical" layer is an option in maps.google.com, but only the "live" traffic seems to be available through the Google Maps API ([documentation](https://developers.google.com/maps/documentation/javascript/trafficlayer#maps_layer_traffic-typescriptl)).

**Comment by dcooley** [comment]
Yeah I don't think this is possible
