### ISSUE TITLE
Question : update map position in shiny app

### ISSUE THREAD

**Issue by chalioui** [SymbolixAU/googleway#230]
Hi! 
There is any way to update the initial starting position of the map by providing a  vector of latitude/longitude and a zoom level in a shiny app ? 

Thank you

**Comment by dcooley** [comment]
The `google_map()` function has both a `location` and a `zoom` argument for this.

**Comment by chalioui** [comment]
Yes, but how we can update it in a shiny app using google_map_update ?

**Comment by dcooley** [comment]
Good question. At the moment I think the only way to do this is by supplying data to one of the `add_*()` layers, as the view will update to where your data is.

**Comment by dcooley** [comment]
as per [this comment](https://github.com/SymbolixAU/googleway/issues/130#issuecomment-1102297395) there is now a `google_map_view()` function for updating the view
