### ISSUE TITLE
Retrieve URL from google_map_directions()

### ISSUE THREAD

**Issue by tom-parkinson** [SymbolixAU/googleway#231]
Thanks for a great package! I have a loop that runs through a list of waypoints and uses `google_map_directions` to open Google Maps directions for each 10 waypoints. It works well, but what I'd really like is the constructed URL from the function. Is there an easy way to return that rather than calling browseURL?

**Comment by dcooley** [comment]
You can't do this directly from a function, but you can construct it yourself if you copy the function `directions_data()` from [here](https://github.com/SymbolixAU/googleway/blob/master/R/googleway-package.R#L31), and using the `bause_url = "https://maps.googleapis.com/maps/api/directions/json?"`, then returning when you've [constructed the URL](https://github.com/SymbolixAU/googleway/blob/master/R/googleway-package.R#L115)

(I haven't tested this works, but that's the general idea).

**Comment by tom-parkinson** [comment]
Awesome. Thanks for the tip!
