### ISSUE TITLE
Google Geocode returns multiple values for latitude and longitude for certain addresses

### ISSUE THREAD

**Issue by Adrianf23** [SymbolixAU/googleway#232]
Here is an example of an address that returns multiple values:

Cooseman's Chicago:

```r
debug <- googleway::google_geocode(
"Coosemans Chicago, Inc.\nChicago Intl. Produce Market\n2404 S Wolcott Ave Unit 13.\nChicago, IL 60608-5341")
```

`debug[["results"]][["geometry"]][["location"]][["lat"]]`
returns

`[1] 41.84585 41.84540 41.84816`

I know this corresponds to the addresses listed here

`debug[["results"]][["formatted_address"]]`
```
[1] "2404 S Wolcott Ave STE 13, Chicago, IL 60608, USA" "2404 S Wolcott Ave STE 22, Chicago, IL 60608, USA"
[3] "2404 S Wolcott Ave, Chicago, IL 60608, USA" 

```

This could also be about how the data is formated (with newline characters \n) because this address works when I paste it as is without the formatting. However, my data all comes in this format and I will be constantly adding new addresses so I'd prefer a way to get back one result. Let me know if you have any more questions.

**Comment by dcooley** [comment]
> Let me know if you have any more questions.

What is the actual issue you're asking me to address?

**Comment by Adrianf23** [comment]
> > Let me know if you have any more questions.
> 
> What is the actual issue you're asking me to address?

I would like to know if you can fix the issue with the function `google_geocode` returning multiple latitudinal/longitudinal points for a given address.

**Comment by dcooley** [comment]
oh. That's not an actual issue, it's what Google gives you from its geocoding service. `googleway` is just the messenger so there's nothing it can do.

**Comment by Adrianf23** [comment]
That makes sense. Thank you

**Comment by dcooley** [comment]
you're welcome 👍
