### ISSUE TITLE
List of Google API's data SKUs that are triggered

### ISSUE THREAD

**Issue by maisonml** [SymbolixAU/googleway#234]
`places <- google_places(search_string = "search term", 
                           location = j,
                           radius = i,
                           key = key)`

For the above sample google_places function from the googleway package, is there a way in R to find the list of Google Maps Places API's data SKUs that are triggered?

Thank you!

**Comment by dcooley** [comment]
Hi @maisonml, forgive my ignorance, but what's an SKU? If it's in the [official documents](https://developers.google.com/maps/documentation/places/web-service/overview) then yes we can get it. Otherwise it's unlikely.

**Comment by dcooley** [comment]
@maisonml please reopen if still relevant.
