### ISSUE TITLE
issue in working under proxy

### ISSUE THREAD

**Issue by spedygiorgio** [SymbolixAU/googleway#24]
I am facing issues in calling the package under proxy:
Error in open.connection(con, "rb") : Couldn't resolve host name

I tried to call: 
```
library(httr)
set_config(
  use_proxy(url="myproxy", port=80,
            username="myusername",password="mypass")
)
```
then call

```
mykeyKey='mykey'
library(googleway)

df <- google_geocode(address = "Via G. Pogliani 6 Paderno Dugnano",
                     key = mykeyKey,
                     simplify = TRUE)
```

without results...

Is it possible to find a workaround?

**Comment by SymbolixAU** [comment]
Is this a `googleway` specific problem - can you access other data through the proxy, for example:

```
library(jsonlite)
res <- fromJSON("https://api.github.com/repos/SymbolixAU/googleway/issues/24")
res$title
# [1] "issue in working under proxy"
res$user$login
# [1] "spedygiorgio"
```

**Comment by spedygiorgio** [comment]
its a problem of mine connection

**Comment by SymbolixAU** [comment]
@spedygiorgio - seems like you're not the only one requesting this - please see issue #26 - are you able to download using `curl::curl()` ?
