### ISSUE TITLE
Is it possible to set basemap with google_map() to sattelite?

### ISSUE THREAD

**Issue by thruesen** [SymbolixAU/googleway#240]
Hi,

I see that it is possible to set basemap as a parameter in google_map_url(), but not in google_map().
I need the map in my shiny application to default to satellite basemap.
(Ref: https://developers.google.com/maps/documentation/javascript/maptypes)

Is there any way to do this with googleway?

Brgds.
Michael

**Comment by dcooley** [comment]
yes - this will be available in the next CRAN release (in the next few days), or you can grab it from github now

```r
remotes::install_github("SymbolixAU/googleway")

set_key( secret::get_secret("GOOGLE") )
google_map(map_type = "satellite")
```
![Screenshot 2022-01-17 at 9 04 28 am](https://user-images.githubusercontent.com/8093396/149679891-d44b2c15-7b33-4c8b-b6d8-52a3156b082c.png)
