### ISSUE TITLE
google_places function doesn't retrieve elements in list but returns valid url.

### ISSUE THREAD

**Issue by neraunzaran** [SymbolixAU/googleway#241]
Hi, I recently discover googleway package and start to play around with it.

In this first exercise i made two requests to the API just just to "see" how the things works. I queryied the API for "stores" (using place_type argument) near my house, and for gas stations in a location i know very well (using serch:string argument), the idea is kept the data in new list object called "storesSDX" and "gas1". 

But surprinsigly, the created objects were created empty and the console returns to me only the url from the API where the data is available. You can see a screenshot below.

![Googleway](https://user-images.githubusercontent.com/7490958/150696016-b805de7e-f7ad-40db-8566-e3a98933adc9.png)

Just to be sure, i've copied and open the url address in my browser and it returns the data i ask for in the query.
Below a screenshot  of the web page

![imagen](https://user-images.githubusercontent.com/7490958/150695735-2209f531-e231-4b43-9255-76a396f9b15b.png)

I dont know if i'm doing something wrong (i've coded using the examples included within the package docs). I will appreciate any corrections if i'm not doing the things in the right way. 

Thanks in advance for your time reading this issue.
Best regards from Guatemala.

Neri Martinez

**Comment by dcooley** [comment]
Hi Neri, 

Thanks for reporting this; you have found a bug that I should have cleaned up before submitting to CRAN. 

If you try the latest github version it should work

```r
remotes::install_github("SymbolixAU/googleway")
```

---

A new version will be on CRAN in a day or two.

**Comment by neraunzaran** [comment]
Wow, i'm amazed on your quick response. First time in my life i found a bug! Thanks for fix through developer package.
I will perform again the toy example.

Thanks fro your great work.

Best Regards.

Neri

**Comment by dcooley** [comment]
2.7.6 is now on CRAN. Please let me know if this issues is fixed for you.

Thanks.

**Comment by neraunzaran** [comment]
Again, thanks.
Now it's working like a charm!!!

I guess this solve the issue and happily it can be closed. :)

Best regards from Guatemala.

Neri

![imagen](https://user-images.githubusercontent.com/7490958/150897680-64274164-8f3a-45ae-9839-7ee2d5677328.png)
