### ISSUE TITLE
Is it possible to set max bounds for the google_map?

### ISSUE THREAD

**Issue by BursacPetar** [SymbolixAU/googleway#242]
Hi, 
I am building one Shiny app and i want to limit google_map to specific boundaries.
Please let me know is it possible to set boundaries - max bounds for the purpose of limiting map area (something like setMaxBounds in leaflet package).

Thanks!
Kind regards, 
Petar

**Comment by dcooley** [comment]
I've just made a prototype on branch `issue242` where you can specify the `min_zoom` and `max_zoom` arguments. 

Could you test this and let me know if it works for you?

```r
remotes::install_github("SymbolixAU/google", ref = "issue242")

## example
set_key("your key")

  google_map(
    min_zoom = 8
    , max_zoom = 12
  )
```

**Comment by BursacPetar** [comment]
Hi, 
Thank you very much for quick answer.
Great, yes it works, but i am also interested in setting bounds in geographical space - limit the map pan? Please let me know is this possible, to set something like min_latitude, max_latitude, min_longitude and max_longitude and in that way to limit map pan?
Thanks!

**Comment by BursacPetar** [comment]
Hi @dcooley ,
I found this in google maps platform. That's exactly what I need. Is it at all possible to implement this within the googleway package.
![image](https://user-images.githubusercontent.com/29697508/151544427-8abf5b1a-14c7-4369-b126-725a5075dbc3.png)

Thanks!

**Comment by dcooley** [comment]
yes that is possible - sorry I've been off work the last few days so haven't got to this.

I've just pushed a commit to branch `issue242` with code that I _think_ should work, but I haven't tested it. Feel free to test & update the branch with a PR if you need to, or if you can wait until Monday I should be able to take a proper run at it then.

**Comment by BursacPetar** [comment]
Hi @dcooley, 
Thank you for your answer. Great! 
Unfortunately i can't make changes to branch 242, i dont have permissions. 
I found this as typing errors (comma is missing in file google_map.js) and this is now working (map is displayed): 

![image](https://user-images.githubusercontent.com/29697508/151658867-ef242da5-8808-4c0e-a4bf-e29a5e78aea2.png)

The bounds have not yet been applied and I think it is a problem to call the variable x.mapBounds in js like x.mapBounds.south (because map_bounds is dataframe and 'south' is a column, not list element). When bounds is manually write down, it works.

![image](https://user-images.githubusercontent.com/29697508/151659142-a1ba7049-c36a-43e9-a569-e1a0e6b52001.png)

Thanks!

**Comment by dcooley** [comment]
> Unfortunately i can't make changes to branch 242

If you need / want to make changes you can clone the repo, make changes and make a pull-request back into this repo.

---

I've udpated the branch with the necessary fixes. Now this works:

```r
library(sf)
nc <- sf::st_read(system.file("./shape/nc.shp", package = "sf"))

google_map(
  map_bounds = sf::st_bbox(nc)
)
```

**Comment by BursacPetar** [comment]
Thanks! Great, now it works as expected!
