### ISSUE TITLE
Remove labels? 

### ISSUE THREAD

**Issue by camerynbrock** [SymbolixAU/googleway#246]
This package is great! I was wondering if it is possible to remove reference labels (i.e., the strings denoting the cities/states/etc.), or to give them a separate z_index to put on top of polygons/overlays? This would be very helpful if so. 

Thank you!

**Comment by dcooley** [comment]
Are you referring to something similar to [their example](https://developers.google.com/maps/documentation/javascript/examples/hiding-features) where you can show / hide (buttons in the top left corner of the map) feature labels?

**Comment by camerynbrock** [comment]
Hi, thanks for your quick response. That doesn't look like what I mean - what I mean is similar to the option for toggling off and on labels when using the satellite background. 

![image](https://user-images.githubusercontent.com/56104182/164171436-7a959b75-17c4-4020-800a-06d7a8a4cf38.png)

![image](https://user-images.githubusercontent.com/56104182/164171350-2b2830ec-1750-4f4c-aed5-43af593e6266.png)

I am looking for a terrain basemap without labels or the option to put the labels on top of other layers. The reason is because I am using add_overlay to add an image over the map, so the labels beneath the overlay are cut off or not visible at all (screenshots here are from the google maps platform site).  

![image](https://user-images.githubusercontent.com/56104182/164172452-71ccfdb6-0889-49ff-9e8d-79714f2caba4.png)

**Comment by dcooley** [comment]
Oh I see.
I'm not sure I've seen that functionality anywhere in the [google maps docs](https://developers.google.com/maps/documentation/javascript/overview), so I don't know off the top of my head if it's possible or not.

**Comment by camerynbrock** [comment]
Aha - figured this out if anyone else ends up being interested. Used styles code from https://mapstyle.withgoogle.com/

`google_map(key = mapKey)`

![image](https://user-images.githubusercontent.com/56104182/164325717-8a2c69b6-d6c3-44ff-9f19-e2dea965b743.png)

`style <- '[{"elementType": "labels", "stylers": [{"visibility": "off"}]},
  {"featureType": "administrative.neighborhood", "stylers": [{"visibility": "off"}]},
  {"featureType": "road", "stylers": [{"visibility": "off"}]}]'

google_map(key = mapKey,
           styles = style)`

![image](https://user-images.githubusercontent.com/56104182/164325769-b294fd32-fd63-463f-8d67-d70c8cbce238.png)

**Comment by dcooley** [comment]
Does this approach allow you

> the option to put the labels on top of other layers

?
