### ISSUE TITLE
Add the option to optimize waypoints 

### ISSUE THREAD

**Issue by WambuH** [SymbolixAU/googleway#25]
The API offers the option to optimize the waypoints in order to get the best/shortest path via (`optimize:true`) [Link](https://developers.google.com/maps/documentation/directions/intro?hl=en#Waypoints).
It comes in handy especially if you have a lot of unordered waypoints and don't have the possibility to order them beforehand.

Cheers

**Comment by SymbolixAU** [comment]
Good suggestion; will add it in to the development version tomorrow

**Comment by SymbolixAU** [comment]
I've just committed an update to the development master branch to include an `optimise_waypoints` argument. However, I've not fully tested this functionality yet.

**Comment by WambuH** [comment]
Thank you! 
Is is somehow possible to test it or do i have to wait for the milestone release?

**Comment by SymbolixAU** [comment]
you can install the latest development version using

```
# library(devtools)
devtools::install_github("SymbolixAU/googleway")
```
