### ISSUE TITLE
How to store google api key in .Renviron

### ISSUE THREAD

**Issue by jzadra** [SymbolixAU/googleway#253]
Is it possible to store the API key in .Renviron?  If so, what is the variable to set?

**Comment by dcooley** [comment]
> Is it possible to store the API key in .Renviron?

of course - you can store waht you like here. For example: `Sys.setenv("my_api_key" = "xxxxxxx")`

> If so, waht is the variable to set?

You can set whatever you like. But `googleway` doesn't look inside the `environment` for a key, you still have to set it yourself in your script:

```
googleway::set_key(Sys.getenv("my_api_key"))
```
