### ISSUE TITLE
use proxy for google_distance 

### ISSUE THREAD

**Issue by mkmdivy** [SymbolixAU/googleway#26]
Hi, thank you for the wonderful R package. 
Since I am using the company network, I need to use the proxy to receive the data. 
Usually I can set the proxy for library httr or Rcurl, (ggmap uses GET function from httr so I could use proxy for that), I saw that googleway imports curl library so I tried everything I could but I still cannot make it.. Could you let me know how can I set the proxy to use the google_distance function without problem? Thank you 

for google_distance I have a following error
Error in readLines(con) : Couldn't connect to server

and for google_direction I have a following error
Error in open.connection(con, "rb") : Couldn't connect to server

**Comment by SymbolixAU** [comment]
Hi @mkmdivy - can you confirm this is a problem specific to `googleway` by trying my suggestion in issue #24 ?

Thanks.

**Comment by mkmdivy** [comment]
Ah, sorry I didn't know that it was duplicated question.. Well, 

library(jsonlite)
res <- fromJSON("http://api.github.com/repos/SymbolixAU/googleway/issues/24")

doesn't work for me which means I am failing to set the proxy for fromJSON function.. Seems like there's no possible way to set the proxy for fromJSON function for windows. 

So, it's not a problem of googleway, thank you!

**Comment by SymbolixAU** [comment]
@mkmdivy  - how about if you use `curl::curl()` - can you configure your proxy settings as per https://www.r-bloggers.com/curl-0-9-2-tweaks-and-proxies-for-windows/  ?

If that works I could work that into a solution, and seeing as you're not the only person having the issue I think it would be a useful addition

```
con <- curl::curl("https://api.github.com/repos/SymbolixAU/googleway/issues/24")
readLines(con)
```

**Comment by mkmdivy** [comment]
Hi, thank you for your answer! 

```
con <- curl::curl("https://api.github.com/repos/SymbolixAU/googleway/issues/24")
readLines(con)

```
Above line has a same error : Error in readLines(con) : Couldn't connect to server

However, if I do the proxy setting as your link suggested 

```
curl_proxy <- function(url, verbose = TRUE){
  proxy <- ie_get_proxy_for_url(url)
  h <- new_handle(verbose = verbose, proxy = proxy)
  curl(url, handle = h)
}

con <- curl_proxy("http://api.github.com/repos/SymbolixAU/googleway/issues/24")
readLines(con)
```

Then it works

Thanks!

**Comment by SymbolixAU** [comment]
In that case I'll update the package to let users pass in a `curl_proxy`.

**Comment by SymbolixAU** [comment]
@mkmdivy & @spedygiorgio - I've just pushed a commit to the development version where `google_distance()` and `google_directions()` now accept a `curl_proxy` object.  Are you able to test it for me?

You can install the development version using

```
devtools::install_github("SymbolixAU/googleway")

## set up curl proxy
curl_proxy <- function(url, verbose = TRUE){
  proxy <- ie_get_proxy_for_url(url)
  h <- new_handle(verbose = verbose, proxy = proxy)
  curl(url, handle = h)
}

## pass in the proxy object
google_distance(origins, destinations, ...etc..., curl_proxy)
```

**Comment by spedygiorgio** [comment]
Thank you very much.. I will check it as soon as possible. 
Best

**Comment by SymbolixAU** [comment]
@spedygiorgio - thanks. 

I may not have fully understood how the `curl_proxy` works as I've never used it before...

**Comment by mkmdivy** [comment]
Hi, 
Thanks a lot for your effort! 

I ran the following code
```
curl_proxy <- function(url, verbose = TRUE){
  proxy <- ie_get_proxy_for_url(url)
  h <- new_handle(verbose = verbose, proxy = proxy)
  curl(url, handle = h)
}


google_directions(origin = c(-37.8179746, 144.9668636),destination = c(-37.81659, 144.9841), mode ="walking",key = "I put my API",curl_proxy)

```

and the following error appeared

```
Error in directions_data(base_url = "https://maps.googleapis.com/maps/api/directions/json?",  : 
  departure_time must be a POSIXct object
```



Again I ran the following code with google_distance
```
curl_proxy <- function(url, verbose = TRUE){
  proxy <- ie_get_proxy_for_url(url)
  h <- new_handle(verbose = verbose, proxy = proxy)
  curl(url, handle = h)
}


google_distance(origin = c(-37.8179746, 144.9668636),destination = c(-37.81659, 144.9841), mode ="walking",key = "I put my API",curl_proxy)

```

and the following error appeared

```
Error in directions_data(base_url = "https://maps.googleapis.com/maps/api/directions/json?",  : 
  departure_time must be a POSIXct object
```






When I run without curl_proxy like previous version 

```
google_directions(origin = c(-37.8179746, 144.9668636),destination = c(-37.81659, 144.9841), mode ="walking",key = "I put my API")

Error in open.connection(con, "rb") : Couldn't connect to server
```
it gives above error

Thank you, probably there's something wrong when you

**Comment by mkmdivy** [comment]
Ah, sorry, I found out that actually curl_proxy is the function so I needed to put any website so it could extract my proxy setting info. Therefore, I ran again below code

```
google_distance(origins = list(c("Melbourne Airport, Australia"),
                               c("MCG, Melbourne, Australia"),
                               c(-37.81659, 144.9841)),
                destinations = c("Portsea, Melbourne, Australia"),
                key = "my api key",mode='driving',
                simplify = FALSE,curl_proxy='google.com')
```

And hopefully the result came out, but it seems like it's a raw text itself. The result is below, it's long 

```
* Connection #0 to host wsg-proxy.oecd.org left intact
 [1] "{"                                                                               
 [2] "   \"destination_addresses\" : [ \"Portsea VIC 3944, Australia\" ],"             
 [3] "   \"origin_addresses\" : ["                                                     
 [4] "      \"Melbourne Airport VIC 3045, Australia\","                                
 [5] "      \"Jolimont Station, Wellington Cres, East Melbourne VIC 3002, Australia\","
 [6] "      \"175 Wellington Parade, East Melbourne VIC 3002, Australia\""             
 [7] "   ],"                                                                           
 [8] "   \"rows\" : ["                                                                 
 [9] "      {"                                                                         
[10] "         \"elements\" : ["                                                       
[11] "            {"                                                                   
[12] "               \"distance\" : {"                                                 
[13] "                  \"text\" : \"135 km\","                                        
[14] "                  \"value\" : 135242"                                            
[15] "               },"                                                               
[16] "               \"duration\" : {"                                                 
[17] "                  \"text\" : \"1 hour 41 mins\","                                
[18] "                  \"value\" : 6074"                                              
[19] "               },"                                                               
[20] "               \"duration_in_traffic\" : {"                                      
[21] "                  \"text\" : \"1 hour 44 mins\","                                
[22] "                  \"value\" : 6247"                                              
[23] "               },"                                                               
[24] "               \"status\" : \"OK\""                                              
[25] "            }"                                                                   
[26] "         ]"                                                                      
        
and more and more until line 68
```

Thank you!

**Comment by SymbolixAU** [comment]
yes, that's the raw JSON returned from Google's API. When you use `simplify = TRUE`, it simplifies it (into a data.frame or list) using `jsontlite::fromJSON()`

**Comment by SymbolixAU** [comment]
Although, I have to say I'm surprised it worked, as that wasn't how I thought it *should* work

**Comment by RedGoalAuthor** [comment]
Hi SymbolixAU - Thanks for adding the proxy connection to google_distance. It works with the argument curl_proxy = 'google.com'

However, I can see that in other functions such as google_places, you haven't added curl_proxy as an argument. Please add, as I am facing proxy issues in other functions of googleway.

**Comment by SymbolixAU** [comment]
Thanks for the suggestion @RedGoalAuthor . Can you please install the version I've pushed to the 'proxy' branch and let me know if that works for you?

```
devtools::install_github("SymbolixAU/googleway", ref = "proxy")
```

**Comment by SymbolixAU** [comment]
Now merged into master

**Comment by RedGoalAuthor** [comment]
Hi Symbolix, I am unable to install the github version.

> devtools::install_github("SymbolixAU/googleway", ref = "proxy")
> Downloading GitHub repo SymbolixAU/googleway@proxy
> from URL https://api.github.com/repos/SymbolixAU/googleway/zipball/proxy
> WARNING: Rtools is required to build R packages, but is not currently installed.
> 
> Please download and install Rtools 3.4 from http://cran.r-project.org/bin/windows/Rtools/.
> Installation failed: Could not find build tools necessary to build googleway

Kindly help, and let me know if the googleway package in CRAN can be updated in any way. It would be a big help.

Thanks.

**Comment by SymbolixAU** [comment]
@RedGoalAuthor 
As per the error message, on Windows to use `devtools` you need to install `Rtools`

**Comment by RedGoalAuthor** [comment]
Thanks, I am checking with my IT to get it installed.

**Comment by SymbolixAU** [comment]
@RedGoalAuthor  
you could also try using `githubinstall` package https://cran.r-project.org/web/packages/githubinstall/index.html

**Comment by RedGoalAuthor** [comment]
Sure, installing RTools worked... Thanks! Let me get back to my project now. :)

**Comment by fsiola** [comment]
Is there a date for curl_proxy on google_geocode be on CRAN?

**Comment by SymbolixAU** [comment]
@fsiola [v2.4](https://www.symbolix.com.au/blog-main/2018) was released on 2nd Feb 2018. All the `google_` functions should now have a `curl_proxy` argument.
