### ISSUE TITLE
Error with batch searches using google_places()

### ISSUE THREAD

**Issue by alexandragibbons** [SymbolixAU/googleway#262]
Hello! I am using google_places to search for facilities in batches. The code to do this is: 

```r
set_key(key = key)
facility2013_searchresults <- pmap(list(facility2013_searchterms$search), googleway::google_places)
```

It usually works, but over the past couple of days I've been getting this error: 

```
"Error in value[[3L]](cond) : 
  There was an error downloading results. Please manually check the following URL is valid by entering it into a browswer. If valid, please file a bug report citing this URL (note: your API key has been removed, so you will need to add that back in)"
```

When I test the URL below the error message it works fine. The URL cited in the error is different each time. Any ideas about what this could be? I am not using a firewall or anything like that and my key is working. Thank you for your help!

**Comment by dcooley** [comment]
what is `pmap` and what does it do?

**Comment by dcooley** [comment]
what was the resolution to this?
