### ISSUE TITLE
Canvas Mode

### ISSUE THREAD

**Issue by OlexiyPukhov** [SymbolixAU/googleway#265]
Is there anyway to get canvas mode of rendering?

**Comment by dcooley** [comment]
what is 'canvas mode of rendering'?

**Comment by OlexiyPukhov** [comment]
It's a way of rendering that makes it less laggy when plotting a lot of circles or markers. It's less well known but it works really well. https://stackoverflow.com/questions/49235357/is-there-a-way-to-implement-canvas-as-renderer-in-leaflet-r-instead-of-svg

**Comment by dcooley** [comment]
I usually recommend people to use [mapdeck layers](https://symbolixau.github.io/mapdeck/articles/google_map.html) on top of a google map, as that's far more performant again.

**Comment by OlexiyPukhov** [comment]
It's a good method, but it doesn't have a function to add circles. Specifically, I want to add all 5000 pharmacies in Ontario on a map and then display information parsed as HTML about it. Mapbox doesn't have that functionality, but leaflet does. Was wondering if its also possible to get that functionality with googleway, but it can't render more than 150 markers/circles.

**Comment by dcooley** [comment]
`mapdeck::add_scatterplot()` will render circles, and it can handle a million points easily

**Comment by OlexiyPukhov** [comment]
Okay, I'll try that and then will update you. Thanks for the help.

**Comment by OlexiyPukhov** [comment]
I got it to work, but the tooltip is not showing up. I initially tried add_scatterplot(), but it did not resize the size of the circles when zooming into the map. I ended up going with pointclouds, since they do resize when you zoom into the map. However, I can't get the tooltip to show. Here is my code so far:

    output$map <- renderGoogle_map({
        google_map(data = pharmacies_data_geocleaned, key = map_key ) %>% 
            mapdeck::add_dependencies() %>% 
            mapdeck::add_pointcloud(
                data = pharmacies_data_geocleaned,
                lon = "long",
                lat = "lat",
                radius = 10,
                tooltip = pharmacies_data_geocleaned$label,
                auto_highlight = TRUE,
                update_view = TRUE,
                id = "google_map",
                focus_layer = TRUE
            )
    })
}

ChatGPT is confused and is not sure what to do. Here are the first 5 rows of pharmacies_data_geocleaned$label (this is all public information)

 [1] "Name: 108 Stop Pharmacy<br>Type: Independent<br>Address: 13444 108 Ave Surrey, BC V3T 2K1 <br>Manager: Vesna Vlacina Ljepic<br>Phone: (604) 957-0711"              
[2] "Name: 360care Denman Pharmacy<br>Type: Independent<br>Address: 683 Denman St Vancouver, BC V6G 2L3 <br>Manager: Cathy Wang<br>Phone: (604) 683-6933"               
[3] "Name: 49th Parallel Pharmacy<br>Type: Independent<br>Address: 15229 Russell Ave White Rock, BC V4B 5C3 <br>Manager: Mary Mani<br>Phone: (778) 294-7737"            
[4] "Name: Aaronson's Pharmacy (Cook St.) Ltd.<br>Type: Independent<br>Address: 1711 Cook St. Victoria, BC V8T 3P2 <br>Manager: Andrew Formosa<br>Phone: (250) 383-6511"
[5] "Name: Abbotsford Pharmacy<br>Type: Independent<br>Address: 104 - 2596 McMillan Rd Abbotsford, BC V3G 1C4 <br>Manager: Benyamin Ghali<br>Phone: (778) 314-1014"

**Comment by dcooley** [comment]
`tooltip = "label"`

**Comment by dcooley** [comment]
`tooltip = "label"` should work. 

Does the example in `?add_pointcloud` work?

```r
df <- capitals
df$z <- sample(10000:10000000, size = nrow(df))

googleway::google_map(key = "abc") %>%
	mapdeck::add_dependencies() %>%
	mapdeck::add_pointcloud(
		data = df
		, lon = 'lon'
		, lat = 'lat'
		, elevation = 'z'
		, layer_id = 'point'
		, fill_colour = "country"
		, tooltip = "country"
	)
```

**Comment by OlexiyPukhov** [comment]
It does not work. For reference, I am trying to do this in a shiny app. The only 2 things that I have changed so far from the example code you linked above is changing it to rendergoogle_map and added my API key. It gives me an error: here is the output and here's my whole code.

library(rio)
library(ggplot2)
library(tidyverse)
library(tidygeocoder)
library(maps)
library(mapdeck)
library(shiny)
library(htmltools)
library(janitor)
library(googleway)
library(mapboxer)
library(shinydashboard)

ui <- fluidPage(
    titlePanel("Testing Google Maps"),
    google_mapOutput(outputId = "map", width = "100%", height = "800px"),
)

server <- function(input, output) {
        pharmacies_data_geocleaned = read_rds("map_bc.rds")
    
    map_key <- "xxx"
    
    df <- capitals
    df$z <- sample(10000:10000000, size = nrow(df))

    output$map <- googleway::renderGoogle_map({(key = map_key) %>%
        mapdeck::add_dependencies() %>%
        mapdeck::add_pointcloud(
            data = df
            , lon = 'lon'
            , lat = 'lat'
            , elevation = 'z'
            , layer_id = 'point'
            , tooltip = "country"
        )})
    
    
    
}

shinyApp(ui, server)

Listening on http://127.0.0.1:4885
Warning: Error in $: $ operator is invalid for atomic vectors
  104: unique
  103: mapdeck::add_dependencies
  102: lapply
  101: sapply
  100: addDependency
   99: mapdeck::add_pointcloud
   98: %>%
   97: ::
htmlwidgets
shinyRenderWidget [C:/Users/Administrator/Desktop/R/BC Pharmaceutical Census/BC_Map_Server_Circles_google_testv2.R#27]
   96: func
   83: renderFunc
   82: output$map
    1: runApp

**Comment by dcooley** [comment]
you haven't included the `google_map()` call

**Comment by OlexiyPukhov** [comment]
Same issue. 
![image](https://user-images.githubusercontent.com/98609419/224848733-99908a8b-d9b7-4576-b608-43bc9bc0ca03.png)

**Comment by dcooley** [comment]
`sessionInfo()` ?

**Comment by OlexiyPukhov** [comment]
![image](https://user-images.githubusercontent.com/98609419/224849139-f4943ee1-ee4e-481a-b83a-beaed7b80c78.png)

**Comment by OlexiyPukhov** [comment]
After running the initial library lines: 
![image](https://user-images.githubusercontent.com/98609419/224849268-b69deb47-bc58-4f3e-8f5b-05063a84ff61.png)

**Comment by dcooley** [comment]
do you have the same versions of these:

```
devtools::session_info("sfheaders")

─ Packages ──────────────────────────────────────────────────────────────────────────────────────────
 package    * version date (UTC) lib source
 geometries   0.2.2   2023-02-28 [1] CRAN (R 4.2.0)
 Rcpp         1.0.10  2023-01-22 [1] CRAN (R 4.2.0)
 sfheaders    0.4.2   2023-03-03 [1] CRAN (R 4.2.0)

 [1] /Library/Frameworks/R.framework/Versions/4.2/Resources/library

```

**Comment by OlexiyPukhov** [comment]
The same. 
![image](https://user-images.githubusercontent.com/98609419/224851147-b9f61116-a160-484f-9b9f-4b041f03a9c9.png)

**Comment by dcooley** [comment]
does this crash?

```
library(mapdeck)

df <- capitals
df$z <- sample(10000:10000000, size = nrow(df))

mapdeck::mapdeck() %>%
  mapdeck::add_pointcloud(
    data = df
    , lon = 'lon'
    , lat = 'lat'
    , elevation = 'z'
    , layer_id = 'point'
    , fill_colour = "country"
    , tooltip = "country"
  )
```

**Comment by OlexiyPukhov** [comment]
It gets stuck computing something. 
![image](https://user-images.githubusercontent.com/98609419/224853576-da9a0df7-f28e-42a0-850f-c8f51c9d3d89.png)

**Comment by OlexiyPukhov** [comment]
Tried again with a fresh R session: this time, it crashed. 
![image](https://user-images.githubusercontent.com/98609419/224853946-2dae4dc6-a42e-4a09-922e-b777c1f8733e.png)

**Comment by dcooley** [comment]
can you try

- restart R session again
- re-install dependencies and dev versions:
   - `remotes::install_github("SymbolixAU/spatialwidget")`
   - `remotes::install_github("SymbolixAU/mapdeck")`
- then try the example again?

**Comment by OlexiyPukhov** [comment]
Still crashes :( 
![image](https://user-images.githubusercontent.com/98609419/224855645-fc41b588-886a-4853-b497-d643b57e2951.png)

**Comment by OlexiyPukhov** [comment]
BUT THE SHINY WORKS! 
![image](https://user-images.githubusercontent.com/98609419/224855919-5a95039a-8496-4a6a-9b05-f5f5f48474ec.png)

**Comment by OlexiyPukhov** [comment]
However, making the fill a string doesn't seem to work. 
![image](https://user-images.githubusercontent.com/98609419/224858569-a0dbdc4d-f77a-45b5-9b96-9437f688d38d.png)

**Comment by OlexiyPukhov** [comment]
Thank you for your help so far! I asked ChatGPT 4 released just today and it solved my issue. Thanks for your help!
