### ISSUE TITLE
Keyless entry

### ISSUE THREAD

**Issue by jonocarroll** [SymbolixAU/googleway#27]
I'm planning on using `googleway` to add some route-estimating functionality to [`ubeR`](https://github.com/DataWookie/ubeR) (see https://github.com/DataWookie/ubeR/issues/1) but of course not everyone has a Google Maps API key. 

Thus:
1. Is it possible to use the service without an API key (presumably with some limitations) and if so, can this be an option in `googleway` functions?
2. Otherwise, what do you think of creating a hardcoded `googleway` API key (limited access, read-only, dedicated account) with a request to not abuse it? I'm sure I've seen this in a package somewhere, but can't recall where.
3. That API key could be specific to either `googleway` or `ubeR`, I just thought I'd run it by you first.

Alternatively, I'll just have it fail if the user doesn't have a valid key. That's not too harsh given that they need to be able to get an Uber API key anyway.

**Comment by SymbolixAU** [comment]
@jonocarroll  It *is* technically possible to call Google's API without a key. However, all their documentation now states you need a key, they've just left in the ability to not have one for backwards compatibility. 

Therefore, while Google's position is that they require you to have a key, I'm going to make `googleway` users require a key too. 

I'm not against the idea of having a 'hardcoded' package key, but, I've got a few other features I want to get implemented first (like the getting the map fully functional!), so it will be low on my priority list at the moment.

**Comment by jonocarroll** [comment]
Fair enough. I've just tested with `key = ""` and sure enough it works fine. I think I'll just reflect your implementation and allow the use of a key, but default to `key = ""`.
