### ISSUE TITLE
Not finding all places

### ISSUE THREAD

**Issue by TheBiro** [SymbolixAU/googleway#31]
Hi, I'm new to github, so please tell if I'm not using this session in the right way.

I'm using googleway to find nearby places based on a lat/long (first I'll need gas_stations, then general places). I made some tests, and it is not finding all locations, I'll give an example:
_____________________________________________________________________________________________________________

- **The place "Posto 100 %", located in: -6.362805, -39.306283.**

To check if it was in google as a real place, I went to Places API developers page and got the 'Place ID', which is: ChIJHRauPxYeowcRfVIL9Cd29zM

- **First validation:**

I checked the ID on the googleway function to get some info, which was all correct, including the 'gas_station' tag:
```
local_info <- google_place_details(place_id = 'ChIJHRauPxYeowcRfVIL9Cd29zM',
                                                        key = chave)
structure(local_info)
```

- **Second validation:**

Then, I made some tests, trying to find this gas station based on its location within a radius (I tried with 50, 100, 1000 and 5000):
```
gas_stations <- google_places(place_type = 'gas_station',
                                                  location = c(-6.362805, -39.306283),
                                                  radius=1000,
                                                  key = chave)
structure(gas_stations)
```

Which returned some Gas Stations, but not this one.
I also tried using keywords and a search_string, but it was also unsuccessful.
_____________________________________________________________________________________________________________

Do you know why it is not finding this one? Also many other specific establishments?I'm using for Brazil only, is this a problem?

Thanks very much for this awesome package, and I hope you can understand my english.
_____________________________________________________________________________________________________________

EDIT: I've tested with a link provided by developers page, and it is returning this gas station I gave as an example. The inputs where exactly the same (location, radius and type):
https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-6.362805,%20-39.306283&radius=500&types=gas_station&key=YOUR_KEY

**Comment by SymbolixAU** [comment]
Hi @TheBiro 

Firstly, your English is perfect, don't worry about that :)

Secondly, the link you've provided includes your API key, so you may want to remove it.

I'll take a look into this and get back to you

**Comment by SymbolixAU** [comment]
@TheBiro I've just committed an update (commit e6cd1b1) that I think solves your issue. There was an issue with how I was constructing the URL to query the API. 

Let me know if this fixes it for you.

**Comment by TheBiro** [comment]
It's working!
Thanks for your fast response and your tip above.

**Comment by SymbolixAU** [comment]
No, thank you for spotting this!
