### ISSUE TITLE
Radius has no effect in  google_places() search

### ISSUE THREAD

**Issue by SFrav** [SymbolixAU/googleway#50]
In testing it seems as though radius in the google_places function has no effect. Setting it to 1 or 10,000 gives the same result for me.

**Comment by SymbolixAU** [comment]
Do you have an example?

**Comment by SFrav** [comment]
I'm not sure if this point exactly replicates, but in searching for locations nearby points in Kenya it would often return a POI kilometers away even though the radius was set to 1m

google_places(location = c(-1.19257949, 36.84516),
                    search_string = "school",
                    radius = 1,
                    key = key)

**Comment by SymbolixAU** [comment]
As you're using the `search_string` parameter, you are performing a **text search**, where the `radius` parameter only biases the results, it doesn't limit them:

>Results inside of this region will be ranked higher than results outside of the search circle; however, prominent results from outside of the search radius may be included

[Reference: Google's API Documentation](https://developers.google.com/places/web-service/search)

For the radius to take effect you need to use a **nearby search** by using the `location` and a `keyword` to limit the results. 

for example

```
google_places(location = c(-1.19257949, 36.84516),
              keyword = "school",
              radius = 1,
              key = key)

google_places(location = c(-1.19257949, 36.84516),
              keyword = "school",
              radius = 1000,
              key = key)
```

Now, having said that, you've highlighted to me that the example for the [nearby search in the vignette is incorrect](https://github.com/SymbolixAU/googleway/blob/master/vignettes/googleway-vignette.Rmd#example---nearby)!

**Comment by SFrav** [comment]
That explains it. Thank you!
