### ISSUE TITLE
Precision of coordinates

### ISSUE THREAD

**Issue by Gh0stSG1** [SymbolixAU/googleway#53]
Currently I'm working on some visualisations on the workings of intersections (traffic lights). The default precision of jsonlite::toJSON of 4 digits is too low for that. For other inner city related projecs the default precision is too low as well (e.g. building contours, locating GPS equipped objects, etc.).

Please add a parameter 'digits' to the add_polylines function (and friends / similar functions) that is passed to the digits parameter of the toJSON function (default value = 4). This approach gives fine control of the number of digits used for each time a function is used. A global "options" variable for 'digits' is another solution, but gives less (or at least counterintuitive) control.

Perhaps another solution is even better and perhaps I have missed something that enables higher precision allready. I couldn't find a global paramter for jsonlite (only stetting through 'digits' directly in the toJSON function). 

To check the solution, I 'hacked' a copy of googleway and replaced the toJSON function with one of my own with a higher default and that did the trick for me.

**Comment by SymbolixAU** [comment]
An alternative solution for now would be to encode the polylines before plotting. This will avoid the precision issue, and reduce the amount of data used in the plot too.

**Comment by Gh0stSG1** [comment]
Ah yes, of course. I tryed to stay close to datastructures I use for Leaflet so I can easily switch depending on the precise requirements. But of course polylines is the default way to go for google maps. I'll give the polylines a go. Thank you.

**Comment by SymbolixAU** [comment]
@Gh0stSG1 - I've given the map layers a `digits` parameter, which gets passed to `jsonlite::toJSON()`. I think this is a useful addition.
