### ISSUE TITLE
Add "icon" argument to add_markers

### ISSUE THREAD

**Issue by misaugstad** [SymbolixAU/googleway#54]
There is an icon argument in the Google Maps APIs for adding a custom image to be used for the marker instead of the default. This would be super useful and (I think) not too hard to implement.

**Comment by SymbolixAU** [comment]
yes - this would be useful. For the simple case I think you just need to supply a url to an image, so this should just be another argument to the `add_markers()` function.

**Comment by SymbolixAU** [comment]
Yes, it was quite easy ([commit #55](https://github.com/SymbolixAU/googleway/pull/55))

```
df <- structure(list(lat = c(-37.8201904296875, -37.8197288513184,
-37.8191299438477, -37.8187675476074, -37.8186187744141, -37.8181076049805
), lon = c(144.968612670898, 144.968414306641, 144.968139648438,
144.967971801758, 144.967864990234, 144.967636108398), weight = c(31.5698964400217,
97.1629025738221, 58.9051092562731, 76.3215389118996, 37.8982300488278,
77.1501972114202), opacity = c(0.2, 0.2, 0.2, 0.2, 0.2, 0.2)), .Names = c("lat",
"lon", "weight", "opacity"), row.names = 379:384, class = "data.frame")

df$icon <- "https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png"

google_map(key = map_key, data = df) %>%
  add_markers(lat = "lat", lon = "lon", info_window = "weight", marker_icon = 'icon')

```
![marker_image](https://cloud.githubusercontent.com/assets/18344164/26563209/dd07a022-4511-11e7-8cb2-e3a552f9d569.png)

**Comment by SymbolixAU** [comment]
will still need to test for locally-stored files/images, and (complex icons](https://developers.google.com/maps/documentation/javascript/markers#complex_icons) too

**Comment by misaugstad** [comment]
I can confirm that it works on local images, provided they are in a 'www' subdirectory. Thanks for the great and quick work!

**Comment by SymbolixAU** [comment]
perfect - thanks!

I'll keep this issue open while I get the complex icons working too.

**Comment by SymbolixAU** [comment]
@misaugstad would you be able to share the code you used to load a marker icon from a local 'www' directory, I can't seem to get it to work?

**Comment by misaugstad** [comment]
[Here is the code](https://github.com/manaswis/sidewalk-chi2018/tree/master/ground_truth_tool)

You don't have access to the data used so you can't run it, but you can see the file structure and what string I am passing in.

**Comment by SymbolixAU** [comment]
@misaugstad  thanks - I had it at the wrong level. 

Also, you might want to hide your API key in a file, rather than have it sitting in server.R

**Comment by misaugstad** [comment]
Ah yes, thank you :)
