### ISSUE TITLE
waypoints

### ISSUE THREAD

**Issue by SymbolixAU** [SymbolixAU/googleway#59]
to accept a `place_id`

**Comment by mohitvkulkarni** [comment]
I've a dataframe which has latitude and longitudes as two different columns. How do I add them as my waypoints? For waypoints, list of vectors needs to be given, how do I do that?
Thanks.

**Comment by SymbolixAU** [comment]
@mohitvkulkarni You're after something like this : [data.frame rows to list](https://stackoverflow.com/q/3492379/5977215). 

Please note that this issue tracker is not the appropriate platform to ask for general help, it's for tracking issues that are specific to the `googleway` package/code.
