### ISSUE TITLE
URL Encoding

### ISSUE THREAD

**Issue by SymbolixAU** [SymbolixAU/googleway#65]
(received via email)

This is not working (only single selection):
avoid = c("TOLLS", "highways")
 
I found the issue to google. They have written that you must use %7C to join 2 or more restrictions in avoid. May you check it?
 
https://issuetracker.google.com/issues/35829648

**Comment by SymbolixAU** [comment]
testing with

```
apiKey <- symbolix.utils::apiKey()


avoidAll <- google_directions(origin = c(47.2887119,1.367837),
                  destination = c(43.68359, -0.598476),
                  mode = "driving",
                  alternatives = TRUE,
                  avoid = c("tolls", "highways"),
                  key = apiKey)


avoidHighways <- google_directions(origin = c(47.2887119,1.367837),
                              destination = c(43.68359, -0.598476),
                              mode = "driving",
                              alternatives = TRUE,
                              avoid = c("highways"),
                              key = apiKey)

avoidTolls <- google_directions(origin = c(47.2887119,1.367837),
                                destination = c(43.68359, -0.598476),
                                mode = "driving",
                                alternatives = TRUE,
                                avoid = c("tolls"),
                                key = apiKey)


df <- data.frame(polyline = c(
  avoidAll$routes$overview_polyline$points,       ## 3 routes - blue
  avoidHighways$routes$overview_polyline$points,  ## 2 routes - red
  avoidTolls$routes$overview_polyline$points),    ## 2 routes - green
  colour = c(rep("#0000FF",3),rep("#FF0000",2),rep("#00FF00",2)))

mapKey <- symbolix.utils::mapKey()

google_map(key = mapKey) %>%
  add_polylines(data = df, polyline = "polyline", stroke_opacity = 0.4,
                stroke_colour = "colour", stroke_weight = 4)
```

![screen shot 2017-08-09 at 7 59 54 am](https://user-images.githubusercontent.com/18344164/29096568-da9da03a-7cd8-11e7-8f7d-829635d43fad.png)

**Comment by AdamKarol** [comment]
Hi, thanks for answear!
Please compare avoid=NULL with avoid=c(“tolls”, “highways”). It seems to be the same results. I think blue lines are along highways (A10 and A65 as A usually means 'highway').

**Comment by SymbolixAU** [comment]
@AdamKarol  - Ah yes, I see the issue - please try my latest commit

```
avoidAll <- google_directions(origin = c(47.2887119,1.367837),
                              destination = c(43.68359, -0.598476),
                              mode = "driving",
                              alternatives = TRUE,
                              avoid = c("tolls", "highways"),
                              key = apiKey)


avoidHighways <- google_directions(origin = c(47.2887119,1.367837),
                                   destination = c(43.68359, -0.598476),
                                   mode = "driving",
                                   alternatives = TRUE,
                                   avoid = c("highways"),
                                   key = apiKey)

avoidTolls <- google_directions(origin = c(47.2887119,1.367837),
                                destination = c(43.68359, -0.598476),
                                mode = "driving",
                                alternatives = TRUE,
                                avoid = c("tolls"),
                                key = apiKey)

avoidNull <- google_directions(origin = c(47.2887119,1.367837),
                               destination = c(43.68359, -0.598476),
                               mode = "driving",
                               alternatives = TRUE,
                               avoid = NULL,
                               key = apiKey)

avoidAll$routes$summary
# [1] "D674" "N21"  "D708"

avoidHighways$routes$summary
# [1] "D674" "N21"  "D708"

avoidTolls$routes$summary
# [1] "N10"          "N10 and D834" "A20 and N10"

avoidNull$routes$summary
# [1] "A10"         "N10"         "N10 and A65"
```

**Comment by AdamKarol** [comment]
Hi, I think it works! I need couple more days to test it on query for few thousand directions (for PL)  with all options.   Thank you very much for quick cooperation.   Adam Karolewski    Dnia 10 sierpnia 2017 23:55 SymbolixAU &lt;notifications@github.com&gt; napisał(a):  github.com @AdamKarol  - Ah yes, I see the issue - please try my latest commit  avoidAll &lt;- google_directions(origin = c(47.2887119,1.367837),
                              destination = c(43.68359, -0.598476),
                              mode = &#34;driving&#34;,
                              alternatives = TRUE,
                              avoid = c(&#34;tolls&#34;, &#34;highways&#34;),
                              key = apiKey)


avoidHighways &lt;- google_directions(origin = c(47.2887119,1.367837),
                                   destination = c(43.68359, -0.598476),
                                   mode = &#34;driving&#34;,
                                   alternatives = TRUE,
                                   avoid = c(&#34;highways&#34;),
                                   key = apiKey)

avoidTolls &lt;- google_directions(origin = c(47.2887119,1.367837),
                                destination = c(43.68359, -0.598476),
                                mode = &#34;driving&#34;,
                                alternatives = TRUE,
                                avoid = c(&#34;tolls&#34;),
                                key = apiKey)

avoidNull &lt;- google_directions(origin = c(47.2887119,1.367837),
                               destination = c(43.68359, -0.598476),
                               mode = &#34;driving&#34;,
                               alternatives = TRUE,
                               avoid = NULL,
                               key = apiKey)

avoidAll$routes$summa [1] &#34;D674&#34; &#34;N21&#34;  &#34;D708&#34;

avoidHighways$routes$s [1] &#34;D674&#34; &#34;N21&#34;  &#34;D708&#34;

avoidTolls$routes$summ [1] &#34;N10&#34;          &#34;N10 and D834&#34; &#34;A20 and N10&#34;

avoidNull$routes$summary [1] &#34;A10&#34;         &#34;N10&#34;         &#34;N10 and A65&#34;

**Comment by SymbolixAU** [comment]
@AdamKarol - How are your tests going? If it's all working I'll close this issue.
