### ISSUE TITLE
Issue with correct distance when passing a list

### ISSUE THREAD

**Issue by alequintos** [SymbolixAU/googleway#72]
Hi,

I've been running some examples and whenever I ask for the distance between 1 origin and 1 destination, the package works fine, but when I try to use a list (for example 3 origins and 3 destinations), I am getting incorrect results. Except for the 1st distance, that one seems to be computed just fine. How do these distances are calculated? In a pairwise form, i.e.: the 1st element of the "origin list" with the 1st element of the "destination list"? or how?

Thanks!

**Comment by SymbolixAU** [comment]
Hi @alequintos  -  Can you provide an example query / code you're using that gives the incorrect results?

**Comment by alequintos** [comment]
Sure! Try this:

ori<-list(c(40.73381, -73.98788), c(40.75802, -73.96861))
des<-list(c(40.74459, -73.98475), c(40.75290, -73.96689))

results<-google_distance(origins = ori,
                          destinations = des,
                          key = "YOUR KEY",
                          simplify = TRUE, mode="driving", units = "metric")

Note the result for the second element of the list and now try running element by element, i.e.

ori<-list(c(40.75802, -73.96861))
des<-list(c(40.75290, -73.96689))

results.1<-google_distance(origins = ori,
                              destinations = des,
                              key = "YOUR KEY",
                              simplify = TRUE, mode="driving", units = "metric")

If you check with the manual request to Google Maps, you'll notice what I am saying.

Thanks!

**Comment by SymbolixAU** [comment]
I think you've misinterpreted the results; you need to go 'deeper' into the `results$rows$elements` to extract the results

```
results$rows$elements
[[1]]
  distance.text distance.value duration.text duration.value duration_in_traffic.text duration_in_traffic.value status
1        1.7 km           1689        8 mins            508                   8 mins                       492     OK
2        3.3 km           3265       13 mins            771                  21 mins                      1246     OK

[[2]]
  distance.text distance.value duration.text duration.value duration_in_traffic.text duration_in_traffic.value status
1        2.8 km           2826       12 mins            743                  24 mins                      1463     OK
2        4.4 km           4424       12 mins            747                  18 mins                      1061     OK

> results.1$rows$elements
[[1]]
  distance.text distance.value duration.text duration.value duration_in_traffic.text duration_in_traffic.value status
1        4.4 km           4424       12 mins            747                  18 mins                      1084     OK
```

If you set `simplify = FALSE` you an see the raw JSON that's returned, and it may be easier to understand what's returned.

**Comment by alequintos** [comment]
ohhh!!! Thanks!! I am so sorry! I see what you mean. So, I think the function is computing all possible combinations, right?? Is there any option to only get 1 vs 1, 2 vs 2, 3 vs 3 and so on?

**Comment by SymbolixAU** [comment]
no, I don't think that's possible using the [distance api](https://developers.google.com/maps/documentation/distance-matrix/intro#DistanceMatrixResponses) in one query. You'd have to do many individual queries.

**Comment by alequintos** [comment]
alright! Thanks for your prompt reply!
