### ISSUE TITLE
Can waypoints in directions_data be modified to allow encoded polylines?

### ISSUE THREAD

**Issue by sokabayashi** [SymbolixAU/googleway#88]
The [Google Maps API](https://developers.google.com/maps/documentation/directions/intro#Waypoints) says:

> Alternatively, you can supply an encoded set of coordinates using the Encoded Polyline Algorithm. This is particularly useful if you have a large number of waypoints, because the URL is significantly shorter when using an encoded polyline.
> 
> Encoded polylines must be prefixed with enc: and followed by a colon (:).For example: waypoints=enc:gfo}EtohhU:

It would be so great if this format of waypoints was possible here!  

Thank you for this wonderful package.

**Comment by SymbolixAU** [comment]
A good suggestion - I'll add it to the 2.4 milestone

**Comment by SymbolixAU** [comment]
@sokabayashi It should actually work as it is, you just need to include the correct formatting with the `enc:` and `:` values

for example

```
waypoints = list(via = paste0("enc:", polyline, ":"))
```

I still need to update the package to make it clear, but for now it should work for you. 

![screen shot 2017-10-27 at 8 22 18 am](https://user-images.githubusercontent.com/18344164/32077723-22638dd0-baf0-11e7-8e1a-3e08f73cd867.png)

**Comment by sokabayashi** [comment]
So it does!!  just tried it out.  wonderful wonderful.  Really appreciate your responsiveness!

**Comment by SymbolixAU** [comment]
I'm going to keep this open so it reminds me to update the documentation and examples :)
