### ISSUE TITLE
Traffic_model argument is not passed to the args and map_url

### ISSUE THREAD

**Issue by alptuzel** [SymbolixAU/googleway#94]
Observation:

I try to calculate the distance in the future by passing departure time and traffic model:

google_distance(list(origin), list(destination),mode = "driving", 
                departure_time = my_depart_2, traffic_model = "optimistic", 
                key=key)

**The result is always the same whether it is optimistic, pessimistic or best_guess.**

**Finding in the source code**

I have traced and found which url is sent to the google. Traffic_model parameter is missing since it is not included into the args  in googleway-package.R

I have added it in my local repository then it worked fine:

args <- c(args, "waypoints" = waypoints,
            "departure_time" = departure_time,
            "arrival_time" = arrival_time,
            "alternatives" = alternatives,
            "avoid" = avoid,
            "units" = units,
            "mode" = mode,
            "transit_mode" = transit_mode,
            "transit_routing_preference" = transit_routing_preference,
            **"traffic_model"=traffic_model,**
            "language" = language,
            "region" = region,
            "key" = key)

**Comment by SymbolixAU** [comment]
@alptuzel - thanks for reporting this - I've now added the fix.
