### ISSUE TITLE
mouse_over and info_window do not show anything 

### ISSUE THREAD

**Issue by masoudmsoltani** [SymbolixAU/googleway#98]
I have a dataset similar to the one below;

```
df <- structure(list(latitude = c(31.19194, 32.06556, 32.02392, 31.075, 
         32.40861, 32.1275, 31.17673, 31.48944, 31.24064, 32.12, 32.50778,                                        
         31.07389, 31.85944, 32.25322, 31.04028), longitude = c(-81.34889,                                        
         -81.27222, -81.23705, -83.20194, -80.51333, -80.79194, -81.48258,                                        
         -82.86611, -82.41859, -81.15, -80.79167, -81.41472, -82.59528,                                           
         -81.37083, -83.07472), colour = structure(c(3L, 5L, 5L, 5L, 4L,                                          
         4L, 5L, 4L, 5L, 1L, 4L, 3L, 3L, 5L, 3L), .Label = c("#00FF00",                                           
         "#FF0000", "#FFFF00", "#0000FF", "#FF00FF"), class = "factor"),                                          
             ID = c(261L, 879L, 852L, 770L, 635L, 685L, 976L, 536L, 1099L,                                        
             76L, 640L, 205L, 321L, 948L, 222L)), .Names = c("latitude",                                          
         "longitude", "colour", "ID"), row.names = c(NA, -15L), class = c("tbl_df",                               
         "tbl", "data.frame")) 
```

Trying to plot them and show specific column when hoovering over the point (circles) or clicking on them which I suppose these are the purposes of `mouse_over` and `info_window` arguments, respectively. This is the code:

```
google_map(key = "your api key" , data = df) %>%
  add_circles(lat = "latitude", lon = "longitude",  
              fill_colour  = "colour", radius = 500, stroke_colour = "colour", mouse_over = "ID", info_window = "ID")
```

But when I hoover over them nothing pops up and when I click on each circle, only a blank window appears.

**Comment by SymbolixAU** [comment]
For **info window**

From `?add_circles`, the `info_window` "needs to be a character", Google Maps doesn't display numerics in info windows, so use

    df$ID <- as.character(df$ID)

For **mouse_over**

I'll have a look into this...

**Comment by SymbolixAU** [comment]
I've just pushed a commit to fix the `mouse_over` issue for circles.  Please try the latest dev version:

```
devtools::install_github("SymbolixAU/googleway")
```
In this version you can also map colours to variables, so there's no need to specify the colours yourself (although you can if you want to)

```
google_map(key = mapKey() , data = df) %>% 
	add_circles(fill_colour = "ID",
			stroke_colour = "ID",
			mouse_over = "ID", 
			info_window = "ID", 
			radius = 1000)
```

**Comment by SymbolixAU** [comment]
Ok, I found the issue regarding `tbl_df` and have issued another fix. It was due to [this issue](https://stackoverflow.com/a/39920059/5977215)

**Comment by masoudmsoltani** [comment]
Thank you. Tested and it works. 

Just one suggestion/request. If we could pass the column names as variables rather than character names that would make things easier. Like avoid to alter the original dataframe for using `info.window`.

**Comment by SymbolixAU** [comment]
Do you mean, in stead of using

```
google_map(data = tram_stops, key = 'mapkey') %>%
  add_markers(lat = "stop_lat", lon = "stop_lon")
```
you would do 
```
google_map(data = tram_stops, key = 'mapkey') %>%
  add_markers(lat = stop_lat , lon = stop_lon)
```
where the `stop_lat` and `stop_lon` are un-quoted?

**Comment by masoudmsoltani** [comment]
I would rather prefer to do that. Because then I can also do this:

`google_map(data = tram_stops, key = 'mapkey') %>%
  add_markers(lat = stop_lat , lon = stop_lon, info.window = as.character(df$ID))`

**Comment by SymbolixAU** [comment]
I see your point, and have thought about that in the past too. 

It might also be useful to convert to character internally within the `add_` functions, which I think will be an easier win for now.

**Comment by masoudmsoltani** [comment]
As you say yourself, for now it is a good improvement for now. But that may be good thing to change since then you can change the variables within the function which may have more use than just `info_window`. Cheers and thanks.
